### ISSUE TITLE
Look for lockfile when manifest file is specified for analysis

### ISSUE THREAD

**Issue by cd-work** [phylum-dev/cli#1027]
Currently manifest files are not accepted at all as lockfiles for analysis. Rather than implementing methods to generate lockfiles from the manifest file, a good first step would likely be to look if there already is a lockfile in the manifest file's location and use that instead.

If an analysis is run using `test/package.json` for example, we could automatically look for `test/package-lock.json` and `test/yarn.lock`.

This should allow us to already identify manifest files, know about their possible associated lockfiles and switch analysis to those lockfiles from the manifest. After that we only need to implement the actual generation logic to provide support for manifest files without existing lockfiles, though those might land in a different location.

**Comment by kylewillmon** [comment]
I think we'll need to answer a few questions on this behavior.

1. If a user runs `phylum analyze package.json` and `package-lock.json` exists, do we:
    1. Log and automatically switch
    1. Ask the user if they want to switch (or error if stdout isn't a tty)
1. Should there be a flag to override this behavior (in case the user wants us to ignore the lockfile)?
1. Should there be a check to see if the lockfile is up-to-date? Maybe just a naive file timestamp (i.e., mtime) check so that no ecosystem tools are required?

**Comment by cd-work** [comment]
> Ask the user if they want to switch (or error if stdout isn't a tty)

Interactive issue resolution does not seem to be in line with our goals for manifest support. So to me the only option is to log and automatically switch.

> Should there be a flag to override this behavior (in case the user wants us to ignore the lockfile)?

Not a bad idea, though that would be added with the option to generate lockfiles. For this issue specifically you either use the lockfile or you get nothing. So we can just assume the user wanted the lockfile.

> Should there be a check to see if the lockfile is up-to-date? Maybe just a naive file timestamp (i.e., mtime) check so that no ecosystem tools are required?

This also applies to the follow-up and I'm not entirely sure how this is best approached. As a developer I think what would seem most logical to me is to go with the out of date lockfile by default, then update with the flag you mentioned in 2).

The manifest feature itself is aimed at helping developers that either forget or don't know about lockfiles, so with that assumption it should be good **most** of the time to just assume a lockfile should be used if we can find one in place of the manifest.

---

One more thing I'd like to add though is the case where you have multiple lockfiles/manifests. I'm not entirely sure how that should behave. Say you have `a/package.json` and `b/package-lock.json`, without any `.phylum_project` lockfiles or lockfiles on the CLI. This currently would just include `b/package-lock.json`.

So either we look for lockfiles first and **then** look for manifest files. Or we look for lockfiles and manifest files and try to filter for duplicates based on some heuristic (skip manifests in the same directory as lockfiles for example). Which of course gets messy with things like cargo workspaces (lockfile is in root, but subprojects have manifests).
