### ISSUE TITLE
Swap custom 'Renderable' implementation for a serde serializer

### ISSUE THREAD

**Issue by DanielJoyce** [phylum-dev/cli#106]
Renderable is used to provide human readable output when querying Projects/Packages by the cli.

It could instead be replaced with implementing a custom serializer to make use of the existing serde infrastructure.

See https://github.com/serde-rs/example-format/blob/master/src/ser.rs for an example

**Comment by cd-work** [comment]
While I do think the CLI output code should be refactored, I'm not sure a custom `Serializer` is the way to go. A serializer is expected to represent a complete version of a structure in a way that could potentially be deserialized again, while it is possible to `#[serde(skip)]` some fields it's not generally something that should omit the majority of values in favor of providing a "pretty" output.

Generally if we only had a normal and "pretty" format, I'd consider maybe using `Debug` which has the pretty-printing distinction with `{:#?}` built-in. But `Debug` isn't generally something that should be used as the standard println format and it quickly runs into limits when we want more than one output format (see https://github.com/phylum-dev/cli/issues/537).

I think having our own trait is the right way to go, but I think we can combine our `Summarize` and `Renderable` traits and just uniformly implement one trait for all of them. I think having separate methods for each format would be nice, but passing format as parameter would probably work too.

Additionally right now we also have an odd `print_response` error which handles the `Result` returned by the API, but I think we should be able to just get rid of that and propagate errors with `?` instead.
