### ISSUE TITLE
Implement OIDC support for user login and refresh/api tokens

### ISSUE THREAD

**Issue by DanielJoyce** [phylum-dev/cli#107]
We need to port the CLI over to using KeyCloak as a oauth provider, and we need to implement a small part of OIDC to do so.

- [x] Support user registration
- [x] Support user login
- [x] Support a method to obtain addition long lived refresh_tokens, say grabbing a token to use a secret for a CLI install
- [x] Support going to account page so long lived tokens can be revoked
- [x] TODO: Theme that page and others....

**Comment by louislang** [comment]
OIDC support added in https://github.com/phylum-dev/cli/pull/118
