### ISSUE TITLE
Provide failure report in pre-check extensions

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#1093]
# Overview
Each of the current package manager extensions offered by the CLI (`npm`, `pip`, `poetry`, and `yarn`) will report that there was a failure when analyzing the new package(s) to be installed. However, the report is simply that there was a failure and no further detail is provided. Provide more detail as to why the analysis failed.

## Additional Context

Here is an example of the current output:

```
❯ phylum pip install "pyyaml==5.3.1"
[phylum] Finding new dependencies…

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
[phylum] Dependency resolution successful.

[phylum] Analyzing packages…
[phylum] Supply Chain Risk Analysis - FAILURE
```

It _may_ be acceptable to provide a link to the project in the UI, to view the results of the analysis there. Check with @louislang before assuming that is _all_ that is required.

Providing a better report output should be possible when the API provides job evaluation results in a machine readable format (issue and PR are internal, but in progress).

## Acceptance Criteria
- [ ] Each package manager extension provides more analysis failure detail
  - [ ] `pip` extension
  - [ ] `npm` extension
  - [ ] `poetry` extension
  - [ ] `yarn` extension

**Comment by cd-work** [comment]
Upstream has been implemented and this should be implementable now.
