### ISSUE TITLE
Provide ability to opt-out of lockfile generation

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#1094]
# Overview
Manifest support was added in CLI v5.1.0 to allow analyzing manifest files by generating lockfiles on-demand. This issue is to provide (more?) mechanisms for opting out of this behavior.

## Additional Context

If there are already means to opt-out of the lockfile generation (e.g., specifying explicit entries in the `.phylum_project` file), they should be documented more clearly. For example, that could be in the form of an update to a current page on the https://docs.phylum.io/ site or maybe a new page (e.g., KB article for "manifests vs. lockfiles" or perhaps a new Troubleshooting/Tips/FAQ page).

## Acceptance Criteria
- [x] Automatic lockfile generation is retained as the default behavior
- [x] Opting out of automatic lockfile generation is possible for use cases that do not involve the `.phylum_project` file
- [x] Documentation is created/updated to be more clear about the options for opt-out

**Comment by kylewillmon** [comment]
It's hard to know how to implement an opt-out without knowing why a user would want to opt-out...

Here are the use cases that I can imagine:

1. A project is using automatic lockfile detection (i.e., no `.phylum_project` file) and they do not want this detection to pick up manifests
1. A project is concerned about the security of lockfile generators and does not want to run them

The first use case is probably not a good use case for opt-out. Automatic lockfile detection may pick up any number of unwanted files and we are going to need some method to ignore them (e.g., `.phylumignore`). That is not unique to lockfile generation

The second issue is a better one. But those security concerns may be mitigated by sandboxing (see #1103).

Are there any other use cases that I have missed?
