### ISSUE TITLE
Check lockfile generation prerequisites before use

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#1096]
# Overview

Manifest support was added in CLI v5.1.0 to allow analyzing manifest files by generating lockfiles on-demand. The generation process assumes specific tools are installed and available in the environment used to run the Phylum CLI. These are implicit prerequisites. This issue is to make them explicit prerequisites that are enforced before use instead of waiting to fail after assuming they are met.

## Additional Context

It might be useful for `phylum-ci` if a unique error code is returned when prerequisites are not met.

The tools required to convert a manifest file to a lockfile are currently provided in documentation in one place...on the [Analyzing Dependencies page](https://docs.phylum.io/docs/analyzing-dependencies). Maybe a new page is needed (e.g., KB article for "manifests vs. lockfiles" or perhaps a new Troubleshooting/Tips/FAQ page).

There is a different issue for [providing helpful messages when these pre-requisites are not met](https://github.com/phylum-dev/cli/issues/1095).

## Acceptance Criteria
- [ ] Every tool required for lockfile generation is checked for existence before use

**Comment by kylewillmon** [comment]
> It might be useful for phylum-ci if a unique error code is returned when prerequisites are not met.

How would this be useful? Even if you can detect the case, `phylum-ci` won't know which pre-requisite or how to fix the issue. So detecting it can't really improve the error message.

> Every tool required for lockfile generation is checked for existence before use

We can already detect this case without a check before use because `Command::spawn()` fails. The error message could be better (and that is captured in #1095). But checking first instead of detecting the failure provides no other benefits and introduces a race condition.

**Comment by maxrake** [comment]
> How would this be useful? Even if you can detect the case, `phylum-ci` won't know which pre-requisite or how to fix the issue. So detecting it can't really improve the error message.

[This pattern](https://github.com/phylum-dev/phylum-ci/blob/main/src/phylum/ci/ci_base.py#L352-L365) came to mind at the time, but maybe that doesn't translate when handling a `phylum parse` command. The idea there, and a few other spots where it shows up, is to "condense" an otherwise ugly stack trace from printing by using a summary of the error instead. In this case, that would remove valuable information.

#47 and #245 are related and exist to improve the situation overall.

> We can already detect this case without a check before use because `Command::spawn()` fails.

`Command::spawn()` has been observed to "fail to fail" in certain situations.

**Comment by kylewillmon** [comment]
> `Command::spawn()` has been observed to ["fail to fail"](https://github.com/rust-lang/rust/issues/90825) in certain situations...like in the `phylum-ci` Docker image.

This occurs because `phylum-ci` only ships amd64 images. CLI currently supports both amd64 and arm64. If this is truly an issue, `phylum-ci` should consider adding linux/arm64 images. Architecture emulation is inefficient and buggy.

**Comment by kylewillmon** [comment]
I believe this is completely resolved by #1099 (apart from the qemu bug that is out of scope).
