### ISSUE TITLE
Check lockfile generation prerequisite versions before use

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#1097]
# Overview

Manifest support was added in CLI v5.1.0 to allow analyzing manifest files by generating lockfiles on-demand. The generation process assumes specific tools are installed and available in the environment used to run the Phylum CLI. These are implicit prerequisites with features provided by implicit version ranges. This issue is to ensure the expected version(s) are enforced before use instead of waiting to fail after assuming a correct version.

## Additional Context

The tools required to convert a manifest file to a lockfile are currently provided in documentation in one place...on the [Analyzing Dependencies page](https://docs.phylum.io/docs/analyzing-dependencies). Maybe a new page is needed (e.g., KB article for "manifests vs. lockfiles" or perhaps a new Troubleshooting/Tips/FAQ page) where a more nuanced discussion of the prerequisite tools and their supported version ranges can take place.

For example, the `pip` lockfile type uses `pip-compile` from the `pip-tools` Python package to convert Python manifests to lockfiles. However, `pip-tools` has [specific version compatibility ranges](https://pip-tools.readthedocs.io/en/latest/#versions-and-compatibility) for both `pip` and Python. It is possible that a user has `pip-tools` installed but with an incompatible version of `pip`.

There is a different issue for [providing helpful messages when these pre-requisites are not met](https://github.com/phylum-dev/cli/issues/1095).

## Acceptance Criteria
- [ ] Supported version ranges for every tool required for lockfile generation is checked before use

**Comment by kylewillmon** [comment]
> This issue is to ensure the expected version(s) are enforced before use

As far as I know, none of our generators requires a particularly recent version of any tool.

It would require a significant amount of research to determine what version of each tool is needed. And I'm not sure that research will actually help anyone.

> It is possible that a user has pip-tools installed but with an incompatible version of pip.

This goes even further than looking at the version of `pip-tools`. If they've install `pip-tools` with an incompatible version of `pip`, that's a broken installation... I'm not sure that detecting that is within the scope of our project.

**Comment by maxrake** [comment]
Good points. Swapping code changes with documentation updates might be acceptable here. If the https://docs.phylum.io/docs/lockfile-generation page that is discussed in #1095 comes to pass, it may be enough to have links to each lockfile generator tool's documentation listed there.

**Comment by kylewillmon** [comment]
I believe the concerns were resolved in #1099. If there are more specific concerns for a specific tool, we can re-open this issue or open a new issue
