### ISSUE TITLE
pip lockfiles with hashes are treated as manifest files

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#1117]
# Overview
When parsing a python lockfile generated with `pip-compile --generate-hashes` the Phylum CLI treats it as a manifest file and attempts to generate a lockfile. This extra step adds more places for failure and isn't needed as the provided file is already a lockfile.

# How To Reproduce
Steps to reproduce this behavior:
1. Create a simple loose requirements file `echo flask > requirements.in`
2. Use `pip-compile` to generate the lockfile with hashes `pip-compile --generate-hashes requirements.in`
3. Parse the resultant lockfile `phylum parse requirements.txt`
4. See the Phylum CLI generate a lockfile

# Expected Behavior
Since the resultant file is a lockfile, I would expect the Phylum CLI tool to use it and not attempt to generate another one.

# Additional Context
While this may not seem like much of an issue, it does create additional places for things to go wrong. Two examples were observed so far.
1. A user attempted to analyze one of these files via `phylum-ci` using the current `v.5.2.0` and did not have `pip-tools` installed on their runner causing a failure. This should be solved by the deprecation of the `pip-tools` requirement in `v.5.3.0-rc1` (once a full release is made), but was an unnecessary failure.
2. When testing this I ran into a `pip` issue. While this isn't a Phylum issue, it does break the parse command and the generation step is unnecessary, so this error should be avoidable.

**Comment by maxrake** [comment]
> 2. When testing this I ran into a `pip` issue. While this isn't a Phylum issue, it does break the parse command and the generation step is unnecessary, so this error should be avoidable.

FYI...this was the [pip issue](https://github.com/pypa/pip/issues/9644).
It can be replicated by following the steps to reproduce _on a Python version less than 3.10_
