### ISSUE TITLE
Host docs with Docusaurus

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#1141]
# Overview

As part of the larger [documentation overhaul story](https://github.com/phylum-dev/roadmap/issues/344), the CLI repo will host it's own documentation. The documentation should be generated as a static site by Docusaurus and hosted on GitHub Pages. The content should be organized in a way that makes sense as a standalone reference even though it will be linked to from the main documentation site at https://docs.phylum.io

## Additional Context

* ~Do not remove the documentation publication step for Readme.com~
  * ~That step will be removed in a different issue, after the new CLI sub-domain is linked to the main docs.phylum.io site~
  * Update: the Readme.com site can continue with stale CLI content for the time it takes to get the new Docusaurus site up; it is okay to remove the `rdme` publication step now
* Work with @louislang to configure the custom domain with the DNS provider
  * Do this **after** adding the custom domain to the GitHub pages site
  * Possible (preferred) sub-domain: `cli.phylum.io`
* The Docusaurus project `package-lock.json` should be included for analysis and dep bumps
* References
  * [Docusaurus docs](https://docusaurus.io/docs)
  * [About GitHub Pages](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages)
  * [Managing a custom domain for a GitHub pages site](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site)

## Acceptance Criteria

* [x] CLI documentation is available at a sub-domain of phylum.io (e.g., https://cli.phylum.io)
* [x] Documentation is generated during the release workflow

**Comment by kylewillmon** [comment]
> generated as a static site by Docusaurus

Are there any alternatives worth considering specifically for CLI? Since we'll be hosted separately, we could potentially use something else. But unless it's significantly better, we should just standardize.

**Comment by maxrake** [comment]
> Are there any alternatives worth considering specifically for CLI? Since we'll be hosted separately, we could potentially use something else. But unless it's significantly better, we should just standardize.

@kylewillmon, [mkdocs](https://www.mkdocs.org/) _might_ be worth considering since it is less complex than Docusaurus, but standardization outweighs that IMO. The other alternatives found appear to be just as complex or more so than Docusaurus. The learning curve for setting up the site "just right" is higher than anticipated, but the ongoing maintenance of the site should be relatively straight forward.

**Comment by maxrake** [comment]
Despite the perceived consensus reached in https://github.com/phylum-dev/documentation/issues/24, it was decided that hosting a _separate_ Docusaurus site at `cli.phylum.io` from the `cli` repo would be undesirable. Instead, a _single_ Docusaurus site at `docs.phylum.io` will be hosted from the `documentation` repo. Source content from the `cli` repo will continue to be hosted there so the docs can live along side the code and be more likely to be updated. A different method for getting that content into the `documentation` repo will be pursued.

Closing this issue now...
