### ISSUE TITLE
SPIKE: Identify a Markdown formatting standard

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#1154]
This repository has a large number of markdown files (`*.md`) and no established standard for formatting and linting those files. This issue is meant to be a research spike only. Possible solutions should be identified, discussed, and documented for reference. The desired end state is a solution reached through consensus, but not implemented. Implementation will happen in a different issue, assuming there is a solution that requires changes.

Goals:

* Standards for formatting and linting documentation files (Markdown) are documented
* Standards are adopted/enforced for the entire company
* Standards are able to be enforced with automation, both locally and in CI
* It might be nice to also account for `*.mdx` files, which are another option for Docusaurus docs

Resources/links:

* Blog: [To Wrap or Not to Wrap: One of Life's Greatest Questions](https://about.gitlab.com/blog/2016/10/11/wrapping-text/)
* Example Markdown style guides
  * [GitLab UI](https://docs.gitlab.com/ee/development/documentation/styleguide/#markdown)
  * [for about.gitlab.com](https://about.gitlab.com/handbook/markdown-guide)
* [Example config file for markdownlint](https://gitlab.com/gitlab-org/gitlab/-/blob/master/.markdownlint.yml)

Some possible tools to consider include:

* [`markdownlint`](https://github.com/DavidAnson/markdownlint)
* [`markdownlint-cli`](https://github.com/igorshubovych/markdownlint-cli)
* [`markdownlint-cli2`](https://github.com/DavidAnson/markdownlint-cli2)
* [EditorConfig](https://editorconfig.org/)
* Others (this list is not exhaustive)

**Comment by cd-work** [comment]
I'm not sure if I would trust in any automatic formatter to get this right, considering there's many things like tables where you **don't** necessarily want to enforce a fixed line limit.

I think the only thing that really needs standardization and a way to automatically apply it is the width of text paragraphs and editorconfig should work great for that.

**Comment by kylewillmon** [comment]
> I think the only thing that really needs standardization and a way to automatically apply it is the width of text paragraphs and editorconfig should work great for that.

If you're referring to the [`max_line_length` property][1] of EditorConfig, it's important to mention that it is only supported by a limited number of editors.

And even though my favorite editor is included in that list, there are notable editors missing (e.g., VS Code).

[1]: https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#max_line_length

**Comment by cd-work** [comment]
> And even though my favorite editor is included in that list, there are notable editors missing (e.g., VS Code).

There's Emacs and Vim, I'm not sure what else one could possibly be using? :stuck_out_tongue_winking_eye:

**Comment by kylewillmon** [comment]
Per discussion above, there is no desire for automatically enforced formatting standards on Markdown files for this project.

As such, I do not believe this ticket is actionable beyond the EditorConfig suggestion, which will be handled in #1191
