### ISSUE TITLE
Lockfile paths should be relative

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#1169]
After ae05e29, CLI is now including lockfile paths when submitting jobs. Unfortunately, the file paths being used are absolute. For example:

```sh-session
> cat .phylum_project 
id: b21c6236-c031-456e-b903-decb6797cf4f
name: cli
created_at: 2023-08-01T14:49:47.493642-05:00
group_name: null
lockfiles:
- path: ./requirements.txt
  type: pip
- path: ./Cargo.lock
  type: cargo
 
> phylum analyze
✅ Successfully parsed lockfile "/Users/kyle/code/cli/./requirements.txt" as type: pip
✅ Successfully parsed lockfile "/Users/kyle/code/cli/./Cargo.lock" as type: cargo
✅ Job ID: 7204e8d6-dd1b-4435-9930-b9cacbe2b93b
```

And those absolute paths show in the UI.

![Absolute path in UI](https://github.com/phylum-dev/cli/assets/616067/4aea6a75-2dc9-418e-8ec0-946774c37f68)

These paths should be relative to avoid leaking user directory information.

**Comment by cd-work** [comment]
Note that relative here should mean relative to the `.phylum_project` file, not relative to some working directory.
