### ISSUE TITLE
Use colorblindness safe colors in terminal

### ISSUE THREAD

**Issue by DanielJoyce** [phylum-dev/cli#120]
It might be worthwhile to consider using colorblind safe colors or techniques in terminal messages

Such as Bold or italic or whatever else ansi term supports.

**Comment by DanielJoyce** [comment]
It looks like ansi-term supports custom colors, so we could use the palettes for the different types and then use those for highlighting, along with disabling color with a NOP pallete.

**Comment by kylewillmon** [comment]
I agree with @cd-work and see no reason to leave this issue open any longer.
