### ISSUE TITLE
`ph init` doesn't automatically identify SBOM files

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#1212]
# Overview
The `ph init` command contains the `type` for `spdx` and `cyclonedx`, but it does not automatically identify the files in the current directory, forcing the user to manually input them.

# How To Reproduce
Steps to reproduce this behavior:
1. Go to a directory that contains a `.cyclonedx` or `.sbom` file
2. Run `ph init` and step through the interactive prompts
3. See that the file is not detected

# Expected Behavior
The `ph init` command identifies and presents `*.sbom` and `*.cyclonedx` files for selection.

# Additional Context
I am not sure if this was intentionally done for some reason I am not immediately seeing.

**Comment by cd-work** [comment]
The lockfile names for CycloneDX are `bom.json` and `bom.xml`, the lockfile names for SPDX are `*.spdx.json`, `*.spdx.yaml`, `*.spdx.yml`, and `*.spdx`.

Neither `*.sbom` or `*.cyclonedx` seem to be standard extensions for these files, which is why this doesn't work.

**Comment by furi0us333** [comment]
Ah, interesting. It seems the issue is with the extensions being used in our SBOM export feature then.

**Comment by furi0us333** [comment]
I tried again with the `*.spdx` extension and it still didn't identify it.
![image](https://github.com/phylum-dev/cli/assets/34108612/a244f570-9d64-4a69-a749-ad69e2538bc8)

I would also recommend we add support for `*.bom.json` as we will export with the project name and label to keep things straight.
![image](https://github.com/phylum-dev/cli/assets/34108612/ece7004a-566f-42c6-aaa9-853971051ad6)
