### ISSUE TITLE
`version` does not display release candidate versions

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#124]
**Describe the bug**
The `version` command does not display release candidate versions.

**To Reproduce**
1. Install a pre-release version of the phylum CLI
2. Run `phylum version`
3. Observe that only the major.minor.patch semver is shown

**Expected behavior**
Display the actual version of the software, including any pre-release semvers

**Screenshots**
![image](https://user-images.githubusercontent.com/34108612/137024033-5ce9cbb6-9743-4a04-83f5-ba0c6da827a8.png)

**Comment by louislang** [comment]
If we want to fix this, we should do it in the build pipeline. We'll need to update the Clap yaml. Perhaps from the Git tag.
