### ISSUE TITLE
Identify manifest files

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#1255]
# Overview

It would be nice to have a way to know if a lockfile detected by the CLI is actually a manifest file. For example, adding a boolean `is_manifest` field to the `lockfile` entries in the output of the `phylum status` command. It would be even nicer if the workspace manifest files were further identified as such.

## Additional Information

This request comes from `phylum-ci`, where it would be helpful to identify manifest files and their type _before_ running an integration. Here is an example of why:

* Top level Workspace manifest files may not get picked up for analysis since they change much less often than the workspace member manifest files
  * Example: A Rust workspace library (e.g., https://github.com/deepcausality-rs/deep_causality) may have a top-level `Cargo.toml` workspace manifest with no dependencies of it's own but plenty of workspace members
    * This manifest hardly ever changes, meaning it won't get picked up for analysis by `phylum-ci` unless the `--force-analysis` option is provided
    * The workspace member packages, where the dependencies _are_ specified, are likely to get updated more regularly
      * These manifests may not be specified in the `.phylum_project` file or as arguments to `phylum-ci` on the command line since some users may (understandably) want to only specify the top-level workspace manifest so as not to have to remember to update the config each time a new member project is added or removed from the workspace
  * Documentation updates were made in https://github.com/phylum-dev/phylum-ci/pull/328 to provide some level of insight as to preferred integration invocation
    * If there was a way to automatically recognize and account for these kinds of manifest files then a pre-emptive action could be taken instead of hoping users read and heed advice in docs and help output

## Acceptance Criteria

- [ ] Manifest files are identified and exposed in the output of a command or `.phylum_project` file
- [ ] Tests are added/updated
- [ ] Documentation is updated

**Comment by kylewillmon** [comment]
To be clear, this is needed because `phylum-ci` doesn't do anything if the file hasn't changed. And, thanks to workspaces, depedencies can change even if the top-level manifest file has not changed.

> For example, adding a boolean `is_manifest` field to the `lockfile` entries in the output of the `phylum status` command.

This option seems simple enough and is probably the way to go. So when `is_manifest` is true, `phylum-ci` will just act as if `--force-analysis` was supplied and always check?

**Comment by maxrake** [comment]
> This option seems simple enough and is probably the way to go. So when `is_manifest` is true, `phylum-ci` will just act as if `--force-analysis` was supplied and always check?

Yes, precisely.
