### ISSUE TITLE
Reconsider of chrono crate due to https://rustsec.org/advisories/RUSTSEC-2020-0071.html

### ISSUE THREAD

**Issue by DanielJoyce** [phylum-dev/cli#134]
I don't we hit the vulnerable code paths, and if we do, we don't use set_env, though we can't make transitive guarantees about crates we consume.

I think we can probably use the time crate ( v > 0.3 ) for our needs. Maybe?

**Comment by kylewillmon** [comment]
As long as we don't enable the `oldtime` feature in `chrono`, it won't pull in the `time` crate and this won't be an issue.

But right now, `xtask` depends on `simplelog` [which uses `chrono`](https://github.com/Drakulix/simplelog.rs/blob/98b0ed6fe52817a824ab839ca32fec1c4da64695/Cargo.toml#L30). And cargo resolves dependencies at the workspace level, so we can't avoid the `time` crate without removing the `xtask -> simplelog` dependency as well.

**Comment by cd-work** [comment]
I don't think we have much control over hitting the vulnerable code paths, but this should be fixed (https://github.com/chronotope/chrono/pull/677) in the [next release of chrono](https://github.com/chronotope/chrono/pull/676).

**Comment by kylewillmon** [comment]
It looks like I was fooled by the [RUSTSEC advisory](https://rustsec.org/advisories/RUSTSEC-2020-0071.html) into thinking this was about the `oldtime` feature of `chrono`... So most of my work on this has been in removing the usage of time v1. [This comment](https://github.com/chronotope/chrono/issues/602#issuecomment-940445390) clears up my misunderstanding...

Luckily, removing duplicate dependencies is a good thing, so my time has not been wasted.

**Comment by cd-work** [comment]
The CVE has been revoked (since technically `chrono` only reads without a lock and doesn't write). And additionally `chrono` now relies on STD's env support to ensure they're covered by STD's lock.

So that should solve all the issues with `chrono`.
