### ISSUE TITLE
Support pnpm lockfile v9

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#1395]
The recent release of [`pnpm v9.0.0`][1] includes a new lockfile version (`v9`). The CLI currently only test our parser against `v6`. We should now add support for `v9`

### Tasks

- [x] Add a `v9` lockfile to our test suite
- [ ] Make any changes as necessary to support both `v6` and `v9` versions

[1]: https://github.com/pnpm/pnpm/releases/tag/v9.0.0

**Comment by cd-work** [comment]
Turns out version 6 and 9 are more different than initially assumed. We'll need to adjust our parser.
