### ISSUE TITLE
Use git info to pre-populate repo url in `ph init`

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#1465]
# Overview
The `init` command has defaults for most things except the repo URL. The idea is to consider using the local git to check for a specified remote that `init` can use as the default value for repo url.

# Acceptance Criteria
- [ ] The `phylum init` command uses local git information to pre-populate a default repo url

**Comment by cd-work** [comment]
All my repositories are cloned through ssh, I'd expect this to be the case for most repositories.
Do you want to suggest `git@github.com:phylum-dev/cli` as repository url in these cases? The existing URLs I've seen were largely HTTP uris.

**Comment by furi0us333** [comment]
I am thinking HTTP is the way to go here. I am a bit indifferent on this feature and don't have a clear objective, it was just a general idea I heard. This is _very_ low priority.
