### ISSUE TITLE
Verified macos developer certificates

### ISSUE THREAD

**Issue by louislang** [phylum-dev/cli#148]
**Describe the issue**
A clear and concise description of the issue.

**Describe why the issue is needed**
A clear and concise description of why the issue needs to be investigated.

**Describe the proposed solution**
A clear and concise description of the proposed solution.

**Estimated Subtasks**
Estimated checklist of subtasks to complete for this issue.

**Additional Information**
Add any other information that might be helpful to better understand this issue.

**Comment by kylewillmon** [comment]
I'm not sure this is necessary. Plenty of other projects (e.g., [`rustup`](https://github.com/rust-lang/rustup), [`starship`](https://github.com/starship/starship), etc.) release binaries for macOS without developer certificates.

**Comment by louislang** [comment]
I think that's fair, most recent installer did not seem to have this issue. Going to close this but we can reopen if we end up needing to do this.
