### ISSUE TITLE
"Update Available" banner shows after a successful update

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#149]
**Describe the bug**
I ran a `phylum update` and it successfully completed.  When I ran the next command, I was prompted with the "Update Available" banner.  This seems like an issue in the version checking logic as I had just updated to the latest stable release.

**To Reproduce**
1. Run `phylum update` to get the latest stable release
2. Run an additional command to see if the "Update Available" banner is displayed
*Note that the banner only displays once per day, so you may have to backdate the timestamp in your `settings.yaml` file to observe it.

**Expected behavior**
Update banner does not display if running on the latest stable build.

**Screenshots**
![image](https://user-images.githubusercontent.com/34108612/144871751-389a84d6-031a-41e8-bd98-ae4173cb01f5.png)

**Comment by eeclfrei** [comment]
This was just due to a failure to update the version in the last tag. Resolved by https://github.com/phylum-dev/cli/releases/tag/v1.1.5
