### ISSUE TITLE
`phylum package` does not indicate unprocessed packages

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#1516]
## Overview

The `phylum package` command does not indicate when a package has been submitted but not processed. Instead, it seems to indicate the package is processed and free of findings.

## How To Reproduce

Steps to reproduce this behavior:

1. Find a package that was recently published
2. Use `phylum package` subcommand to get info on it
3. See that the status appears to be complete, with "Num Vulns" of `0` and "Risk Vectors" of 100

Here is an example, with an `awscli` package uploaded ~1 hour before this attempt:

```
❯ phylum --version
phylum v7.1.1

## What it looks like for a package that has been "submitted" but not "processed"
❯ phylum package pypi awscli 1.35.3

 Package Name:                awscli    Package Version:                           1.35.3
 License:         Apache License 2.0    Last updated:       2024-10-09T19:22:46.332+00:00
 Num Deps:                         6    Num Vulns:                                      0
 Ecosystem:                     pypi


 Risk Vectors:

    Total Risk:              100
    Author Risk:             100
    Engineering Risk:        100
    License Risk:            100
    Malicious Code Risk:     100
    Vulnerability Risk:      100

## What it looks like for a package that has not been "submitted" (doesn't exist in this case)
❯ phylum package pypi awscli 1.35.4
⚠️  Thank you for submitting this package. Please check back later for results.

## What it looks like when analyzing the still unprocessed package
❯ echo "awscli==1.35.3" > requirements-delme.txt

## It shows as "INCOMPLETE" and "unprocessed" ...which is correct/expected
❯ phylum analyze requirements-delme.txt
✅ Successfully parsed dependency file "requirements-delme.txt" as type "pip"
✅ Job ID: 707e53a5-39d3-4044-bc13-fed35561d23e

Phylum Supply Chain Risk Analysis — INCOMPLETE

The analysis contains 1 unprocessed package, preventing a complete risk
analysis. Phylum is currently processing these packages and should complete
soon. Please wait for up to 30 minutes, then re-run the analysis.

You can find the interactive report here:
  https://app.phylum.io/projects/d84b0bb3-fb64-43cb-a473-dc96b54db662?group=integrations&label=uncategorized
```

## Expected Behavior

Some indication is given when the package is still unprocessed by Phylum, like how the UI does it:

<img width="1796" alt="image" src="https://github.com/user-attachments/assets/f95a7303-8790-4163-acce-179bff67da8d">

## Additional Context

None at this time

**Comment by cd-work** [comment]
Just a disclaimer: I've fixed this already but I'm looking into https://github.com/phylum-dev/cli/issues/351 to see if that gets automatically fixed too with some potential API changes.

**Comment by furi0us333** [comment]
Some aspects of this may also be tied to this [story](https://github.com/phylum-dev/roadmap/issues/472)
