### ISSUE TITLE
CLI returns error while API returns success

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#1524]
# Overview
The CLI `package` command returns a "package analysis failed" error, but looking up the same package via the package endpoint succeeds. 

# How To Reproduce
Steps to reproduce this behavior:
1. Run `phylum package nuget pagedlist 1.17.0`
2. See error
3. Look up package via API `https://api.phylum.io/api/v0/data/packages/nuget/pagedlist/1.17.0`
4. See success

# Expected Behavior
Both requests return package details.

# Additional Context
This seems tied to the updated error messaging, but the pipelineStatus seems fine.
![image](https://github.com/user-attachments/assets/36acd68f-1fa6-4668-927d-0638bd4dd1e7)

![image](https://github.com/user-attachments/assets/c4f2d127-2d7c-4d34-bd18-a04aaa84d1c1)

**Comment by kylewillmon** [comment]
CLI actually uses a slightly different endpoint. But the status there is reported the same.

```
> curl -s -H "Authorization: $(php auth token)" "https://api.phylum.io/api/v0/data/packages/nuget/pagedlist/1.17.0" | jq '{ pipelineStatus, pipelineError }'
{
  "pipelineStatus": "Complete",
  "pipelineError": ""
}
```

This appears to be yet another issue of `""` vs `null` ...
