### ISSUE TITLE
Error message text missing

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#154]
**Is your feature request related to a problem? Please describe.**
When submitting a project for analysis with a project file that is not associated with that user account, the user is returned an error, but no longer receives the message text.

**Describe the solution you'd like**
Send the message text so the user can understand why the error occurred.

**Additional context**
The first command is against the current production environment and the error message text is returned.  The second command is against the staging environment and does not get the useful explanation.
![image](https://user-images.githubusercontent.com/34108612/149032401-6c482e1f-1d4d-4a57-bb9f-517125914811.png)

**Comment by furi0us333** [comment]
This might belong in API, so feel free to move if that is more appropriate.

**Comment by louislang** [comment]
In general, we should suppress the error logging and just print the specific error. Instead of `Error submitting package caused by: Server returned non-success status`. This should jus say something like:

```
Failed to analyze the provided project. A project with the name `foobar` does not exist.

To create this project run: phylum projects create <projectName>
To link an existing project run: phylum projects link <projectName>
```

Users shouldn't have to read JSON to figure out what is going on.
