### ISSUE TITLE
Support passing in offline_access token via env var

### ISSUE THREAD

**Issue by DanielJoyce** [phylum-dev/cli#157]
Right now it has to be set in settings yaml

We should support passing it in via env var.

**Comment by peterjmorgan** [comment]
This will be awesome, and prevent the necessity of: 
`sed -i "5 a \  offline_access: ${{ inputs.phylum_token }}" ~/.phylum/settings.yaml`

**Comment by kylewillmon** [comment]
It seems like this is done now based on [this code](https://github.com/phylum-dev/cli/blob/e6a76bf278835e932b58bb14594e488e354b4cf2/cli/src/config.rs#L102)

This may still need documentation and/or testing, though.
