### ISSUE TITLE
The help description for `package-type` in `phylum package` is inaccurate 

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#171]
**Describe the bug**
The help description for the `--package-type` option in the `package` subcommand is inaccurate. The example states "pypi" but the command expects "python". If "pypi" is provided, the search appears to default to npm yielding unexpected (and potentially confusing) results.

**To Reproduce**
1. Run `phylum package -t pypi rsa 4.4`
2. See that you get results from npm
3. Run `phylum package -t python rsa 4.4`
4. See that you get the expected results from pypi

**Expected behavior**
The quick fix would be to update the help to the accepted argument of "python". There is still a bit of misalignment as "ruby" and "python" are languages, but the other accepted type is "npm" which is a registry.  Ideally, everything would be normalized.

**Screenshots**
![image](https://user-images.githubusercontent.com/34108612/151274984-30ae549d-1fad-4202-ac9b-1f5cc05b9b4f.png)

**Comment by maxrake** [comment]
@furi0us333, the `development` branch a/o today no longer appears to exhibit this issue:
```
➜  cli git:(development) target/debug/phylum package -t pypi rsa 4.4

 Package Name:        rsa    Package Version:       4.4
 License:         Unknown    Last updated:            0
 Num Deps:              0    Num Vulns:               0
 Type                PyPI    Language            Python


 Risk Vectors:

    Author Risk:             100
    Engineering Risk:        100
    License Risk:            100
    Malicious Code Risk:     100
    Vulnerability Risk:      100

➜  cli git:(development) target/debug/phylum package -t python rsa 4.4

 Package Name:        rsa    Package Version:       4.4
 License:         Unknown    Last updated:            0
 Num Deps:              0    Num Vulns:               0
 Type                PyPI    Language            Python


 Risk Vectors:

    Author Risk:             100
    Engineering Risk:        100
    License Risk:            100
    Malicious Code Risk:     100
    Vulnerability Risk:      100
```
Consider closing?

**Comment by furi0us333** [comment]
Closing as the help description is no longer inaccurate. We will still need to update `ruby` to `rubygems` at some point as we have normalized on ecosystem name.
