### ISSUE TITLE
Provide support for uninstall

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#206]
# Overview
As a user,
I would like to be able to uninstall the phylum CLI tool,
in order to bring my system back to the state it was in before the phylum CLI tool was installed.

# Acceptance Criteria
- [ ] A command is available to automatically uninstall or, at a minimum, documentation provided to manually uninstall
- [ ] No traces of the phylum CLI tool remain after uninstall
- [ ] All user config files (e.g., profile and rc files) are updated to remove any entries added by the phylum CLI tool install
- [ ] Documentation is updated to describe the process

## Associated User Story
*EDIT:* [CLI Uninstall Script](https://www.notion.so/phylum/CLI-Uninstall-Script-c52c9fc6f486419ab220b3ca1da15afb)

**Comment by furi0us333** [comment]
I believe this is the same/similar to an existing user story https://www.notion.so/phylum/CLI-Uninstall-Script-c52c9fc6f486419ab220b3ca1da15afb
