### ISSUE TITLE
NuGet renders as ".NET" in the CLI

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#212]
# Overview
NuGet submissions via `.csproj` files render as `.NET` in the CLI.

# How To Reproduce
Steps to reproduce this behavior:
1. Submit a C# `.csproj` file for analysis
2. Observe the `Type` and `Language` as `.NET`

# Expected Behavior
This should be changed to `NuGet` to match the convention.

# Additional Context

![image](https://user-images.githubusercontent.com/34108612/160012194-732e45e0-bdbb-4f78-a8a5-b1d3bd28bb7d.png)

**Comment by kylewillmon** [comment]
`Type` should definitely be `NuGet`.... But `Language` seems complicated in this case. Usually `C#`, but sometimes maybe `F#` or even `VB.NET`?

**Comment by furi0us333** [comment]
Agreed, might make more sense longer term to combine them into a new `Ecosystem` field.
