### ISSUE TITLE
Improve `history` subcommand

### ISSUE THREAD

**Issue by louislang** [phylum-dev/cli#22]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A reorganization of the `history` subcommand. Running `ph history` should return the high level help information for this command, along with the list of subcommands of `history` and their descriptions.

_Really_ history is mostly a renaming of the current `status` command with some minor UX improvements.

This command should have several of its own subcommands:

- [x] Setup command scaffolding for subcommands, arguments, etc.
- [x] `ph history` - Should show the 30 most recent runs. 
- [x] `ph history --job <job id>` - Show the full results of a given job
- [x] `ph history project` - Show a list of projects associated with the user
- [x] Update the projects endpoint to support the next task.
- [x] `ph history project <project name>` - Shows the project based history listing
- [x] `ph history project <project name> <job id>` - Shows the full results of a job

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by peterjmorgan** [comment]
@louislang @ambray and I discussed at length. The attached screenshot shows the commands and output for 2 of the subcommands
![image](https://user-images.githubusercontent.com/132468/117174413-898cec80-ad82-11eb-93b2-d8f261543ba1.png)
