### ISSUE TITLE
Improve `analyze` subcommand

### ISSUE THREAD

**Issue by louislang** [phylum-dev/cli#23]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A reorganization of the `analyze` subcommand. Running `ph analyze` should return the high level help information for this command. This command is really a renaming (and slight re-work) of the `submit` command. It takes the following form: 

```
ph analyze <pathToPackageFile.ext> --verbose --json --web
```

The first positional parameter is the path to the `package-lock.json`, `yarn-lock.json`, `requirements.txt`, etc. We currently have separate facilities for processing package files from each ecosystem. These facilities should be rolled into the `ph` binary to minimize friction to getting started.

The default view for this is a summary overview containing things like:
* Number of packages
* Number of packages that fall within certain score ranges (i.e. bar graph style display)
* Worst packages
* Highest score and lowest score

Really, just give the user a feel for their current posture and give them a path to where they should look first. 

The flags for this command are all *optional*.
- `--verbose` - Returns a more verbose response. If `--json` is provided with this flag, give more verbose JSON output. If it is not provided, expand upon our summary and give full package details.
- `--json` - Returns a JSON formatted response
- `--web` - Open the users web browser to the web application for the specified project. (This is a low priority item).

**Note**: The `analyze` subcommand expects to be associated with a project. If we are not currently associated with a project, exit and alert the user to this fact. Provide a helpful message describing how they can create a new project, or how they can link to an existing project.

We should also fetch the configured threshold for the specified project and exit with a non-zero exit code if the threshold is broken.

- [x] Rename `submit` to `analyze`
- [x] Add native support for NPM package lock files
- [x] Add native support for Yarn lock files
- [x] Add native support for Gemfiles
- [ ] Add native support for Python requirements
- [x] Improve help message for missing project
- [x] Query threshold settings
- [x] Add summary output (brief)
- [x] Add summary output (detailed)
- [x] Update default response for summary view (see @peterjmorgan's work for inspiration)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by peterjmorgan** [comment]
@louislang and I were working on the output. This is a screenshot of what we came up with for ```analyze```

Take a look, and let's discuss when you have a moment!
![image](https://user-images.githubusercontent.com/132468/117073765-3d409e80-ace7-11eb-95d1-4be908a879d6.png)
