### ISSUE TITLE
Provide bare token output for `phylum auth token` command

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#252]
# Overview
It would be nice to make it so that the `phylum auth token` command _only_ includes the token as output. Currently, it also includes a checkmark due to use of the [print_user_success macro](https://github.com/phylum-dev/cli/blob/development/cli/src/print.rs#L13):

```sh
❯ phylum auth token
✅ eyJhbGci---TRIMMED---
```

This output is sent to stderr and, because it includes the checkmark, is hard to include in command pipelines.

One possibility is to provide a global option to suppress the status emoji style output for all commands.

Possibly related to #229 

# Acceptance Criteria
- [ ] The output of `phylum auth token` _only_ includes the token
- [ ] The output of `phylum auth token` is written to stdout instead of stderr
- [ ] Related documentation is updated

## Associated User Story
--

**Comment by cd-work** [comment]
I don't think this is the best idea, since I'd advocate to generally remove the checkmark. But one could also check if `phylum` is running in a pipe or not and change the formatting style based on that.
