### ISSUE TITLE
CLI allows "disabling" total project threshold

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#288]
In the `phylum project set-thresholds` command, using a score of 0 (zero) for the "TOTAL PROJECT Threshold" claims that this is "disabling" the threshold:

```
✔ TOTAL PROJECT Threshold · 0

Disabling total project risk domain
```

However, in the UI, there is no option to disable the total project threshold. The individual risk domains all have sliders next to them, but the total project threshold does not:

![total-project-threshold](https://user-images.githubusercontent.com/616067/164749079-54719031-a40f-4e1a-a890-f6ddb47af408.png)

So this threshold is actually enabled with a value of 0

**Comment by cd-work** [comment]
This seems related to https://github.com/phylum-dev/cli/issues/287#issuecomment-1106777889. There's no way to know if a threshold was actually disabled or not.
