### ISSUE TITLE
New `api` subcommand

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#298]
Some other tools that interface with a REST APIs allow accessing generic endpoints with a subcommand. Here are the docs for [`gh api`](https://cli.github.com/manual/gh_api).

It seems like this would be fairly simple to implement and would allow more rapid testing/development of new endpoints. It would also allow future CLI extensions to directly access functionality that is not otherwise available in the CLI.

**Comment by cd-work** [comment]
It seems like `gh api` at least provides some benefit by filling in certain parameters for the user. Is the goal to do a similar thing here with the project for example?

Otherwise I don't see much of an advantage over just using `curl`.

**Comment by kylewillmon** [comment]
The `phylum auth token --bearer` command has proven to be very useful. I regularly find myself doing things like this:

```
curl -vvv -H "Authorization: Bearer $(phylum auth token -b)" https://api.staging.phylum.io/api/v0/data/projects/overview
```

This has made this issue irrelevant (for now at least)
