### ISSUE TITLE
Tab completion does not complete filename in `phylum analyze`

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#299]
Tab completion for `phylum analyze` does not complete filenames. So in a directory with a `requirements.txt` file, if you type:

```
phylum analyze req<TAB>
```

It does not tab complete. The result is that I am required to correctly spell requirements.... And my spelling isn't great.

I have only tested this in `zsh`, so it may not be a problem for `bash`

**Comment by louislang** [comment]
Can confirm I've seen this on `zsh` as well, and it's tremendously annoying. Would be awesome to have a fix for this.

**Comment by kylewillmon** [comment]
We use `clap_complete` to write our tab completion files. Looking at the [example](https://docs.rs/clap_complete/3.1.2/clap_complete/#example), it seems like they use [value_hint](https://docs.rs/clap/3.1.12/clap/struct.Arg.html#method.value_hint) to determine what should be a filename. So this should be a very simple fix of just going through `app.rs` and adding some calls to `value_hint`

**Comment by furi0us333** [comment]
@kylewillmon FWIW, I successfully tab complete this command with `bash` on `WSL`

**Comment by kylewillmon** [comment]
> @kylewillmon FWIW, I successfully tab complete this command with `bash` on `WSL`

Thank you. I had guessed that based on [this comment](https://docs.rs/clap/3.1.12/clap/enum.ValueHint.html#variant.Unknown) about the default behavior.

We could actually consider that a separate bug since `bash` will use filenames in **too many** circumstances. For example:

```
phylum project link foo<TAB>
```

But we can worry about that when we decide to implement tab completion for project names (which we definitely should do at some point).
