### ISSUE TITLE
Installer fails on macOS

### ISSUE THREAD

**Issue by samtay** [phylum-dev/cli#316]
# Overview
Installer is broken on macOS, due to assuming gnu-sed.

# How To Reproduce
Steps to reproduce this behavior:
1. Run installer on mac (without gnu-sed)
2. Observe:
```
❯ ./install.sh 

    phylum-cli installer

sed: 1: "/Users/samtay/.bashrc": bad flag in substitute command: 's'
```

# Expected Behavior
Work out of the box or document that `gsed` should be installed as `sed`.

# Additional Context
Might need a little wrapper that detects `uname` or an ugly `sed -i.bak ; rm file.bak` thing.

**Comment by maxrake** [comment]
Can confirm...except with a little different output:

```sh
❯ ./install.sh

    phylum-cli installer

sed: 1: "/Users/maxrake/.bashrc": command c expects \ followed by text
```

I think this should be addressed/fixed _before_ the next CLI release.

**Comment by maxrake** [comment]
Changing the `install.sh` lines with sed in them from `sed -i'' ...` to `sed -i'.bak' ...` worked...but did leave the `.bak` files in place. I vote for changing the script to work in all environments vs. documenting a pre-requisite for macOS users.
