### ISSUE TITLE
`phylum project create` error

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#331]
# Overview
There seems to be a false error in the new `v3.0.0` around project creation.

# How To Reproduce
Steps to reproduce this behavior:
1. Update to CLI `v3.0.0`
2. Attempt to create a project `phylum project create test`
3. See error for invalid project name, even with simple name

# Expected Behavior
Project names that abide by the stated limitations are accepted.

# Additional Context
![image](https://user-images.githubusercontent.com/34108612/166068654-bf514b33-1783-4ecc-8c3a-fa8fca08fff5.png)

**Comment by cd-work** [comment]
Just to clarify, since the issue sounds like it's something about the `test` project: It seems like no projects can be created regardless of the name used?

**Comment by louislang** [comment]
fwiw, working with `v2.2.0`

```
❯  phylum
phylum v2.2.0
Phylum, Inc.
...

❯  phylum project create test
---------------- Update Available ----------------

A new version of the Phylum CLI is available. Run

        phylum update

to update to the latest version!

--------------------------------------------------


✅ Successfully created new project, test
```
