### ISSUE TITLE
Add support for yarn v2 remote dependencies

### ISSUE THREAD

**Issue by cd-work** [phylum-dev/cli#344]
# Overview

When a remote dependency like http(s)/ssh is specified in the yarn lockfile, the parser currently fails. While remote dependencies aren't analyzed, they shouldn't cause a complete failure.

# How To Reproduce

```
"express@ssh://git@github.com:expressjs/express":
  version: 4.18.1
  resolution: "express@ssh://git@github.com:expressjs/express#commit=d854c43ea177d1faeea56189249fff8c24a764bd"
  checksum: b96b66e0e7134c4c9ed2fdaf1d15397f330586a11fee909054c0705afc1bf976e234d5891d0ec294bb8d7c1872ce04291ed370b2280daee2adb207a5bbd39e67
  languageName: node
  linkType: hard
```

# Expected Behavior

The lockfile should be parsed without any errors, ignoring the remote dependency.

**Comment by kylewillmon** [comment]
> While remote dependencies aren't analyzed, they shouldn't cause a complete failure.

I don't agree with this. If we have dependencies that we don't understand, it seems dangerous to fail silently.

Instead, I think we should add a `--permissive` command-line option that enables the behavior suggested in this issue. By default, we would error if we find any dependencies that we don't understand, but with `--permissive`, we log them and skip them.

**Comment by cd-work** [comment]
> I don't agree with this. If we have dependencies that we don't understand, it seems dangerous to fail silently.

Are you suggesting that by default whenever we encounter any remote or filesystem dependency we cannot analyze, we should fail the build? If so, that seems like a bigger change and one that would require changing all the other parsers.

It's also something I'd consider risky since it goes into the direction of being so annoying and bothering the developers so much, it might turn them away from using phylum. I'd imagine especially local filesystem dependencies aren't uncommon at all.

**Comment by kylewillmon** [comment]
> Are you suggesting that by default whenever we encounter any remote or filesystem dependency we cannot analyze, we should fail the build? If so, that seems like a bigger change and one that would require changing all the other parsers.

Not exactly. I'm saying that we need to be very picky about the dependencies that we silently ignore. Silently ignoring workspace dependencies is very different than silently ignoring VCS dependencies. And if we can't tell what it is, it's safer to err on the side of being annoying.

**Comment by kylewillmon** [comment]
Taking a break from the philosophical conversation to talk more specifically about this issue.

Our Python parsers take the VCS URL and put it in the `version` field and continue with the submission. The `yarn` parser should do the same. The backend currently ignores these dependencies, but that should be changing in the near future.
