### ISSUE TITLE
`phylum parse` subcommand

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#346]
# Overview
Add a subcommand that allows parsing a lock file and returning the parsed dependencies in a structured format

# Acceptance Criteria
- [ ] `phylum parse -t mvn pom.xml` would return JSON of at least the dependency name/version pairs parsed out of the pom.xml file. (this is just an example)

**Comment by kylewillmon** [comment]
Adding a `-t` for the lock file type will require that we give a name to each of the lockfile types that we support. Currently, `phylum analyze` tries to figure it out based on the filename and falls back to trying every parser to see which one works.

I am thinking that it makes sense to use the name of the tool that generates each particular lock file. So that would be:

| Type | Standard file name |
| --- | --- |
| `npm` | `package-lock.json` |
| `yarn` | `yarn.lock` |
| `gem` | `Gemfile.lock` |
| `pip` | `requirements.txt` |
| `pipenv` | `Pipfile` or `Pipfile.lock` |
| `poetry` | `poetry.lock` |
| `nuget` | `*.csproj` |
| `mvn` | `pom.xml` |
| `gradle` | `gradle.lockfile` |

**Comment by furi0us333** [comment]
Seems reasonable to me @kylewillmon 👍

**Comment by peterjmorgan** [comment]
@kylewillmon could we add SPDX export format to this?

**Comment by kylewillmon** [comment]
> @kylewillmon could we add SPDX export format to this?

It's definitely possible, but there are a lot of little details to the SPDX format and they change for each ecosystem and for VCS or other URL-based dependencies.

The plan for this issue was to keep a pretty limited scope, so all of those details should probably be hashed out in a separate issue.
