### ISSUE TITLE
Unhelpful `phylum analyze` output for nonexistent lock file

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#347]
# Overview
A small typo in the filename for the lockfile is an easy mistake to make. But the error message output by `phylum analyze` is very unhelpful and says nothing about the file being nonexistent.

```
❯ phylum analyze reqiurements.txt
[2022-05-04T21:04:44Z WARN  phylum_cli::commands::lock_files] Attempting to obtain packages from unrecognized lockfile type: reqiurements.txt
[2022-05-04T21:04:44Z ERROR phylum] Execution failed: Unable to locate any valid package in package lockfile
❗ Error: Execution failed caused by: Unable to locate any valid package in package lockfile
```

# Expected Behavior
An error message that says something like "file not found"

# Additional Context
I'm asking for a freind of course... I have no truoble at all with my spelling 😅

**Comment by kylewillmon** [comment]
It looks like there has been a regression here after #354 

Here is the current error message that once again says nothing about "file not found"

```
❯ phylum analyze /tmp/xxx
[2022-05-09T18:45:03Z WARN  phylum_cli::commands::lock_files] Attempting to obtain packages from unrecognized lockfile type: /tmp/xxx
[2022-05-09T18:45:03Z ERROR phylum] Execution failed: Unable to locate any valid package in package lockfile
    
    Caused by:
        Failed to identify lockfile type
❗ Error: Execution failed caused by: Unable to locate any valid package in package lockfile
```

**Comment by cd-work** [comment]
@kylewillmon I think this change is unrelated to #354 and due to the current groups changes being tested? At least the code involved is completely unrelated to `lock_files.rs`.

**Comment by kylewillmon** [comment]
> @kylewillmon I think this change is unrelated to #354 and due to the current groups changes being tested? At least the code involved is completely unrelated to `lock_files.rs`.

No. This is a direct result of #354.

Before #354, `try_get_packages()` was using the `?` operator on all of the `Parseable::new()` calls and would return an error if any one of them failed, resulting in the helpful root cause shown in [your example error message](https://github.com/phylum-dev/cli/commit/ebc6789076ade230a108589e04b0904dec3e60c2) (see the [code here](https://github.com/phylum-dev/cli/blob/ddc75251de406ed3151e30aa76b21127cc6ab1b7/cli/src/commands/lock_files.rs#L15))

After #354, the `try_format!` macro no longer uses the `?` operator anywhere and only returns if the parser succeeds. So `try_get_pacakges()` falls continues to the last line of the file where it returns the unhelpful error message found here. (see the [code here](https://github.com/phylum-dev/cli/blob/81f27aecbd2f368c89d9ec4ad84221d5e9ec5a10/cli/src/commands/lock_files.rs#L16))
