### ISSUE TITLE
Extensions: Require slashes for local installs

### ISSUE THREAD

**Issue by andreaphylum** [phylum-dev/cli#356]
Currently, `phylum extension add` will install extensions from a local directory.

In the future, we may have a marketplace of extensions and it would make more sense that `phylum extension add <extension-name>` adds an extension from there.

To ensure that we can distinguish between local and marketplace installations in the future, the `phylum extension add` should enforce a specific format for local installs.

After discussion, we have decided that a local install will be required to use a slash in the `phylum extension add` command. For example:

```
phylum extension add foo          # Install `foo` from marketplace
phylum extension add ./foo        # Install from local directory `foo`
phylum extension add foo/bar      # Install from local directory `foo/bar`
phylum extension add /path/to/foo # Install from local directory `/path/to/foo`
phylum extension add C:\dev\foo   # Install from local directory `C:\dev\foo`
```

## Error message
Since we do not currently support marketplace installs, any `phylum extension add` command that attempt to install from the marketplace will fail with a descriptive error message:

```
❗ Error: Attempting to install from marketplace, which is not yet supported. Did you mean `phylum extension add ./foo`
```

**Comment by cd-work** [comment]
IIRC your current PR looks for an extension file in the directory, but if we force people to specify the file directly we could determine if the extension is a local file or a remote extension name using the CLI argument alone.

**Comment by kylewillmon** [comment]
> so `phylum extension add ./my-plugin/extension.toml` versus `phylum extension add my-plugin`.

What would this be using to make the determination? What happens if `my-plugin` is a valid TOML file in the current directory?

**Comment by cd-work** [comment]
I would just base it solely on the filename. The existing PR already enforces a specific name for the toml file, so we can use that to determine the format?
