### ISSUE TITLE
Consume the new `/.well-known/openid-configuration` redirect endpoint.

### ISSUE THREAD

**Issue by mathew-horner** [phylum-dev/cli#373]
# Overview
I recently [implemented a new API endpoint](https://github.com/phylum-dev/api/pull/222) for redirecting to the Keycloak OpenID configuration. We need to update the CLI to consume this instead of using the `oidc_discovery_url` config value.

# Acceptance Criteria
- [ ] All usages of the `oidc_discovery_url` config value should be replaced by the API endpoint `/.well-known/openid-configuration`.
- [ ] The CLI user should not have to specify the `oidc_discovery_url` config value anymore.

**Comment by kylewillmon** [comment]
For tracking, [this](https://github.com/phylum-dev/api/commit/cd7392348253e11630ae37500f995460a6825071) is the API commit that needs to be in prod before we can release a CLI with this feature.

**Comment by cd-work** [comment]
@kylewillmon Would you suggest waiting for the commit to be in prod before starting this, or feature-gating? I'd imagine the change should be so trivial, it might be more work to add a feature than to just wait.

Also does the old URL still work after this PR, or will the CLI break once that's done?

**Comment by kylewillmon** [comment]
> @kylewillmon Would you suggest waiting for the commit to be in prod before starting this, or feature-gating? I'd imagine the change should be so trivial, it might be more work to add a feature than to just wait.

Waiting makes sense. And we won't be waiting for long. It should be rolled out by Monday.

> Also does the old URL still work after this PR, or will the CLI break once that's done?

The old URL will still work. In fact, the "new URL" is just a shortcut (HTTP 301) to the old URL. This allows us to find the OIDC server directly from the API so that we only have to configure 1 URL.
