### ISSUE TITLE
`phylum history --project` always shows 0 jobs

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#378]
After the latest API updates:

Even when a project has jobs, `phylum history --project <project-name>` shows zero jobs:

```
❯ phylum history --project test
Last 0 runs
```

**Comment by cd-work** [comment]
> Retrieving jobs for a project might be solved by the `/groups/<group_name>/projects/<project_id>` endpoint

> There's already a /data/projects/<project_id> endpoint for user-owned projects

Relevant discussion details from slack^

**Comment by kylewillmon** [comment]
I don't think there is an endpoint that will give us the information we need. The UI uses the `/data/projects/<project_id>/history` endpoint, but it returns very little information:

```
❯ curl -s -H "Authorization: Bearer $(phylum auth token -b)" https://api.staging.phylum.io/api/v0/data/projects/48a69a41-fb58-4317-9538-e248504f6544/history | jq .
[
  {
    "id": "124fc828-93ca-4abd-a834-e8bfef71f019",
    "created": "2022-05-18T21:20:12.351898Z",
    "label": "uncategorized",
    "num_dependencies": 0
  }
]
```

For comparison, here is the `/data/jobs` endpoint.

```
❯ curl -s -H "Authorization: Bearer $(phylum auth token -b)" 'https://api.staging.phylum.io/api/v0/data/jobs?limit=1&verbose=1' | jq .                     
{
  "jobs": [
    {
      "job_id": "124fc828-93ca-4abd-a834-e8bfef71f019",
      "project": "test4",
      "label": "uncategorized",
      "num_dependencies": 1,
      "score": 1,
      "packages": [
        {
          "name": "six",
          "version": "1.0.0",
          "type": "pypi"
        }
      ],
      "pass": true,
      "msg": "Project met threshold requirements",
      "date": "2022-05-18T21:20:12.351898+00:00",
      "ecosystem": "pypi",
      "num_incomplete": 0
    }
  ],
  "total_jobs": 18,
  "count": 1
}
```

**Comment by DanielJoyce** [comment]
@kylewillmon what type of data do you need?

**Comment by DanielJoyce** [comment]
The endpoints were largely built around the needs of UI originally

**Comment by cd-work** [comment]
Currently the CLI has a command which outputs the job history. The `--project` flag was originally meant to provide the job history for just one flag. The job history includes the following data for each job:
 - Analysis score
 - Analysis state (PASS/FAIL/INCOMPLETE)
 - project name, group and ID
 - job start time
 - Job summary ("Project met threshold requirements")
 - Ecosystem
 - Number of analyzed packages

However we've discussed this in our integration sync and I think we're open to making modifications to this too. The UI for example doesn't have a way to show history at all, so it's questionable whether this is a feature we want to either expose in both UIs, or in none, though consistency would probably be good.

Ultimately if a history command is desired going forward too, it would probably make sense to get a quick analysis overview over all jobs for a single project so we don't have to send a bunch of small job analysis requests to the API.

**Comment by DanielJoyce** [comment]
Seems reasonable. I think a history endpoint would be useful for several things.
