### ISSUE TITLE
`phylum` fails to ignore certificates to allow proxying

### ISSUE THREAD

**Issue by peterjmorgan** [phylum-dev/cli#388]
# Overview
The CLI attempts to respect `HTTP_PROXY` and `HTTPS_PROXY` environment variables, but requests subsequently fail even when using the `--no-check-certificate` option. 

# How To Reproduce
1. Configure an HTTP proxy such as Burp on a common port like *:8080
2. In a shell, configure an HTTP Proxy with: `export HTTPS_PROXY=https://localhost:8080`
3. In the same shell session, attempt to use phylum to hit an API endpoint: `phylum auth status`
4. Observe the following error:
```
❯ phylum auth status
[2022-05-18T21:07:59Z WARN  phylum] Ignoring TLS server certificate verification per user request.
[2022-05-18T21:07:59Z WARN  rustls::conn] Sending fatal alert BadCertificate
[2022-05-18T21:07:59Z ERROR phylum] Execution failed: Error creating client

    Caused by:
        0: error sending request for url (https://login.phylum.io/auth/realms/phylum/.well-known/openid-configuration): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
        1: error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
        2: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
❗ Error: Execution failed caused by: Error creating client
```
6. Also, attempt to bypass certificate checking: `phylum --no-check-certificate auth status`
7. Observe the following error:
```
❯ phylum --no-check-certificate auth status
[2022-05-18T21:08:46Z WARN  phylum] Ignoring TLS server certificate verification per user request.
[2022-05-18T21:08:46Z WARN  rustls::conn] Sending fatal alert BadCertificate
[2022-05-18T21:08:46Z ERROR phylum] Execution failed: Error creating client

    Caused by:
        0: error sending request for url (https://login.phylum.io/auth/realms/phylum/.well-known/openid-configuration): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
        1: error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
        2: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
❗ Error: Execution failed caused by: Error creating client
```

# Expected Behavior
When supplying `--no-check-certificate` a proxy offering a self-signed or otherwise invalid certificate should work.

**Comment by kylewillmon** [comment]
Looks like we're only ignoring certificates for the API server and not the OIDC provider (code [here](https://github.com/phylum-dev/cli/blob/main/cli/src/auth/oidc.rs#L208))

This should be simple enough to fix
