### ISSUE TITLE
Phylum UI URL not valid for groups

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#395]
# Overview
The URL provided by the CLI analysis summary will not work without the group information

# How To Reproduce
Steps to reproduce this behavior:
1. Run an `analyze` command with the `project` and `group` options specified
2. Look at the URL for "View in Phylum UI:"
3. Attempt to use that URL and get an error
4. (Optional) Adding `?group=<group_name>` to the end of the URL will work

# Expected Behavior
I don't think people are using the URL from the CLI and I vote to remove this field from the display. If we do decide to keep it, adjustments will be needed to account for groups. Additionally, since group names can be up to 100 characters, we will likely need to leverage a URL shortening service to better control the display.

# Additional Context
![image](https://user-images.githubusercontent.com/34108612/169427040-9a964597-2aa6-4585-a979-8f60edfadf6e.png)

**Comment by janasheehan** [comment]
I suspect the UI link should be fixed rather than deleted... @furi0us333?
