### ISSUE TITLE
Blank "User ID" field in analysis summary

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#396]
# Overview
The "User ID:" field is now blank. This seems to be true whether a `group` is specified or not.
CLI `v3.4.0` against staging

# How To Reproduce
Steps to reproduce this behavior:
1. Run an `analyze` command
2. Notice the blank "User ID:" field

# Expected Behavior
Perhaps change this field to "Owner:" and either display the User or Group as relevant?

# Additional Context
![image](https://user-images.githubusercontent.com/34108612/169427419-f9693003-83db-4ed4-a94a-cc10d6420446.png)

**Comment by cd-work** [comment]
The field `user_email` which was previously used for this is actually empty from the API, with only the `user_id` field being present. I think a user UUID is quite useless for this so I'd suggest moving this ticket to API?
