### ISSUE TITLE
Allow extension upgrades

### ISSUE THREAD

**Issue by andreaphylum** [phylum-dev/cli#400]
We may want to implement the `phylum extension upgrade` subcommand on top of `install`/`uninstall`. In that case, we may allow overwriting the extension installation directory, which we disallow at the moment.

**Comment by cd-work** [comment]
How would that work, just the same as installing, or pulling from some random repo? Do we need an `upgrade` command when it is equivalent to just doing install again?

**Comment by andreaphylum** [comment]
> How would that work, just the same as installing, or pulling from some random repo? Do we need an `upgrade` command when it is equivalent to just doing install again?

I'd say it should be roughly the same as installing, with the added step that one may want to cleanup the extension directory to avoid leaving stale files. On the other hand, `install` would explicitly forbid overwriting files, which would allow us not to risk mixing versions up. I think having the command would make the semantics and intentions more explicit on the user side.
