### ISSUE TITLE
Uniform the style of the `config_dir` and `data_dir` functions

### ISSUE THREAD

**Issue by andreaphylum** [phylum-dev/cli#414]
`data_dir` is a function that resolves the XDG data directory and appears in the [extensions](https://github.com/phylum-dev/cli/blob/andrea/extensions-api/cli/src/config.rs#L193) code. As it is pretty similar to the `config_dir` function, we want to refactor the latter to look more similar to the former, and also correct its call sites to take that into account.

**Comment by kylewillmon** [comment]
Just to clarify, this is talking about these functions:

```
pub fn data_dir() -> Result<PathBuf>
pub fn config_dir(home_path: &Path) -> PathBuf
```

And suggesting using this instead:

```
pub fn data_dir() -> Result<PathBuf>
pub fn config_dir() -> Result<PathBuf>
```

Is that correct?

**Comment by cd-work** [comment]
Another important note: We shouldn't have multiple of these methods. Currently we have two `data_dir` methods.
