### ISSUE TITLE
`analyze` subcommand: Allow user to specify yarn lock filenames not restricted to `yarn.lock`

### ISSUE THREAD

**Issue by peterjmorgan** [phylum-dev/cli#43]
**Is your feature request related to a problem? Please describe.**
`phylum` requires yarn.lock files to named exactly `yarn.lock`. Some customers use yarn.lock files that have other names, which would require them to rename the file prior to submitting. 

**Describe the solution you'd like**
The user specifies the filename as an argument to `phylum analyze` and the cli tool infers the type of the file from the headers present. 

**Describe alternatives you've considered**
An alternative could be to add an option or flag to the cli to specify the lock file type. 

**Additional context**

**Comment by louislang** [comment]
I _think_ the `yarn.lock` file is [auto generated](https://classic.yarnpkg.com/en/docs/yarn-lock/). The assumption being that `yarn` will always produce a `yarn.lock`, with no options to change the name. I suspect that the differing names from customers may be an attempt to differentiate where the `yarn.lock` files came from, and to also avoid any name collisions.

**Comment by eeclfrei** [comment]
I can see how this might be useful when we have a batch of various files to submit though.  Maybe we can leave the existing behavior in place (switch based off well known file name), but then fall back to attempting to guess the type by trying the various parsers here: https://github.com/phylum-dev/cli/blob/a85f2f6f4fec704666cb8b7b2739cb9a44abc8ec/lib/src/bin/phylum-cli.rs#L174 perhaps logging a warning if we do so.
