### ISSUE TITLE
`analyze` submission gives confusing results with number of dependencies compared to number of histogram entries

### ISSUE THREAD

**Issue by peterjmorgan** [phylum-dev/cli#45]
**Describe the bug**
Sometimes when using the `analyze` subcommand, the response shows confusing information when comparing the number of dependencies and the histogram. 

![image](https://user-images.githubusercontent.com/132468/120673966-7e43e400-c448-11eb-9e51-9b0e727dd4dd.png)

**To Reproduce**
1. Submit root9b's packages using `analyze`
2. Note the number of dependencies in the header stats block
3. Note the number of packages listed in the histogram

**Expected behavior**
The number of dependencies is the same as the number of entries in the histogram

**Comment by louislang** [comment]
Confirmed working by @peterjmorgan.
