### ISSUE TITLE
Switch `ubuntu-22.04` runner to `ubuntu-latest` when possible

### ISSUE THREAD

**Issue by cd-work** [phylum-dev/cli#467]
Currently our GitHub CI relies on the `ubuntu-22.04` OS version for some checks. This is a pre-release version and does not represent the latest ubuntu release.

To avoid falling behind when GitHub updates its latest version beyond 22.04, we should switch back to `ubuntu-latest` as soon as that becomes a version greater or equal to 22.04.

**Comment by kylewillmon** [comment]
GitHub has now published [this blog post](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/) on the rollout of `ubuntu-22.04` as `ubuntu-latest`:

> This change will be rolled out over a period of 8 weeks beginning on October 1, 2022.

That 8 week period ends on November 26, 2022, so we should change back to `ubuntu-latest` after that date.
