### ISSUE TITLE
Feature request: an ARM64 build for Linux

### ISSUE THREAD

**Issue by aviflat** [phylum-dev/cli#522]
The project currently publishes builds for ARM64 for Darwin but not for Linux.

For me, an ARM64 build for Linux would be handy.

Thank you!

**Comment by cd-work** [comment]
Out of curiosity, which ARM64 Linux device are you running?

**Comment by aviflat** [comment]
My workstation is an M1 Pro MacBook Pro, but I’m running the CLI on AWS Lambda, so I guess that’d be AWS Graviton2.
