### ISSUE TITLE
Parser `WARN` statements

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#556]
# Overview
Given an `effective-pom.xml` file that has been renamed to `pom.xml` the CLI seems to chose the `pypi` parser and spits out a bunch of `WARN` statements. Note: If the file is not renamed, it processes cleanly.

# How To Reproduce
Steps to reproduce this behavior:
1. Rename an `effective-pom.xml` file to `pom.xml` and submit for analysis
2. See `WARN` messages with "parsers::pypi"

# Expected Behavior
`WARN` message for "unrecognized lockfile type," but correctly determine the maven ecosystem and use that parser.

# Additional Context
![image](https://user-images.githubusercontent.com/34108612/179253929-31219e12-6b9d-455e-aa9e-0f7585761dca.png)
...snip...
![image](https://user-images.githubusercontent.com/34108612/179254480-61664fe5-a0a5-4831-b616-8f5ddd64c0e7.png)

What is interesting is that it seems to have processed correctly and the listed `Ecosystem` is `Maven`

**Comment by cd-work** [comment]
A warning from the `pypi` parser doesn't imply that we've actually detected the file to be a `pypi` file. To determine which type an unknown file has, all parsers actually attempt to parse it and only when the result is a list with at least one properly parsed package, we'll accept the parsing result.

So in this scenario the parser tries to parse everything, fails loudly, and produces no output packages, thus leaving the parsing up to another parser.

I see two possible solutions to these confusing warning messages: Either we stop warning, at the very least when the parser is unknown, so everything behaves the exact same but no messages are emitted. Or we change the parser to fail loudly, this could cause some correct files to not be parsed anymore but returning an error would interrupt the parser's parsing and skip to the next one if the file is unknown.

**Comment by furi0us333** [comment]
Brainstorming:

`WARN` Attempting to obtain packages from unrecognized lockfile type: pom.xml
Attempting to parse as `pypi`: Unsuccessful
Attempting to parse as `yarn`: Unsuccessful
Attempting to parse as `gradle`: Success!
