### ISSUE TITLE
CLI `--json` option includes update notification stanza that breaks JSON format

### ISSUE THREAD

**Issue by peterjmorgan** [phylum-dev/cli#56]
**Describe the bug**
`phylum` has a `--json` option to return JSON formatted data. The update notification stanza breaks JSON format. In its current implementation a user will need to remove that header before the data can be interpreted as JSON with something like:
`phylum analyze myfile.lock --json | taiil -n+9` 

**To Reproduce**
1. Submit with `phylum analyze <lockfile> --json` and pipe to an editor
2. Observe the header

**Expected behavior**
The `--json` option will often be used for automation. It is strongly desirable to ensure the response is well-formed JSON.

**Suggestion**
We could consider adding a key to the JSON output that notifies for the presence of an update to the CLI tool.

**Screenshots**
![image](https://user-images.githubusercontent.com/132468/122991946-734ee600-d35a-11eb-929a-80d89aa9ece0.png)

**Comment by eeclfrei** [comment]
I think we can probably just resolve this by putting the update message on to stderr, so that it won't break pipelines, redirection, etc.
