### ISSUE TITLE
Help output for `phylum extension run` causes error

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#605]
# Overview

The `phylum extension run --help` command results in an error and no help message is displayed.

# How To Reproduce

Steps to reproduce this behavior:
1. With a CLI that includes extensions, run `phylum extension run --help`
2. See error

# Expected Behavior

Running `--help` on any CLI command results in a useful help message

# Additional Context

Screenshot:

![image](https://user-images.githubusercontent.com/18729796/183128182-d0bbef8a-e275-41b3-ba0c-cf0d706f9f16.png)

**Comment by cd-work** [comment]
This is pretty much intentional, since we want to allow passing parameters to `extension run`.
