### ISSUE TITLE
Use `openssl` to verify package instead of `minisign`

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#618]
It is currently possible to install Phylum with a one-liner:

    curl https://sh.phylum.io/ | sh -

But the script requires (by default) that the user have the `minisign` tool installed, which is not common. It should instead use `openssl`, which is much more common.

**Comment by cd-work** [comment]
Is the goal of this ticket just to remove `minisign`, or to provide an alternative? The title sounds a bit like just removal but the description makes it seem more like replacement is the goal.

If we're going for replacement, do we want to nail down the tech to replace it with or is it part of this issue to look into the different technologies available and find a solution?

**Comment by kylewillmon** [comment]
Yes. This ticket is about finding an alternative. I'll update the title and description to reflect that.

**Comment by kylewillmon** [comment]
The alternative is `openssl`. Research complete.

Switching this story to be the actual implementation.
