### ISSUE TITLE
Include default extensions with each release

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#641]
The extensions in the `./extensions` folder should be shipped with the CLI.

## Acceptance Criteria
- [ ] When a user installs the CLI default extensions should automatically be installed
- [ ] When the CLI is updated the extensions should also be updated

## Notes
Because these extensions are maintained by Phylum and automatically installed, we do not need to prompt the user to accept permissions when doing these installs. Also, we can simply overwrite the extensions during upgrade as we do not expect users to modify these extensions.

We should consider adding the ability to skip this in the installer for some environments. Perhaps a command-line argument or environment variable to disable the install of extensions. Ideally, this choice would persist across upgrades.

**Comment by cd-work** [comment]
> When the CLI is updated the extensions should also be updated

Probably want to get https://github.com/phylum-dev/cli/issues/400 sorted out first before tackling this.

**Comment by kylewillmon** [comment]
> Probably want to get #400 sorted out first before tackling this.

It took me too long to see how right this was... I am now putting this issue on hold while I address #400
