### ISSUE TITLE
`PhylumApi.getProjectDetails` does not use groups

### ISSUE THREAD

**Issue by louislang** [phylum-dev/cli#642]
# Overview
Calling `getProjectDetails` in the extension API does not allow you to pass along the group.

# How To Reproduce
### `group-example/main.ts`
```
cat group-example/main.ts
import { PhylumApi } from 'phylum';

const project = await PhylumApi.getProjectDetails("foobarabc");
console.log(project);
```

### Create **group** project and Run Extension
```
❯  phs project create foobarabc --group extensionstest
✅ Successfully created new project, foobarabc

❯  phs extension run ./group-example
Extension error: Uncaught (in promise) Error: HTTP request error (404 Not Found):

could not find any matching resource for the given id
    at async Function.getProjectDetails (deno:phylum:127:16)
    at async file:///Users/louis/Development/PHYLUM/localdev-test/gradle-work/group-example/main.ts:2:17
```

# Expected Behavior
We should be able to query the API for group projects.

# Additional Context
The project appears to 404 due to the fact that we can't specify the group the project is associated with. 

Since projects can be created with groups, we should allow an optional group parameter to `PhylumApi.getProjectDetails`

**Comment by cd-work** [comment]
This is directly related to https://github.com/phylum-dev/cli/issues/378, which also uses the old endpoint without group support.

**Comment by kylewillmon** [comment]
`getProjectDetails()` uses a deprecated endpoint and, as such, should be deprecated itself.

To replace it, we will be adding two new functions:

* `getCurrentProject()`
* `listProjects(group_name?)`
