### ISSUE TITLE
Extensions: Add a `getCurrentProject()` function

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#644]
Many extensions operate within the current project. A `getCurrentProject()` function would help these extensions.

## Acceptance Criteria
- [ ] Function returns project name and group name details from the current `.phylum_project` file
- [ ] Function returns `null` if no `.phylum_project` file is found.

**Comment by kylewillmon** [comment]
I am immediately questioning whether or not this is actually necessary....

The only thing that an extension can do currently with a project name and group name is run `analyze()`. But if an extension wants to run the analyze on the current project, they simply need to pass in `null` for the project name.

Am I missing a use case for this function?

**Comment by cd-work** [comment]
This would be the only offline way to check if you've got a project linked at all for example, you wouldn't necessarily want to run into an API failure for that.

I could also see this being helpful to some projects that have very specific extensions they want to use for multiple of their own projects, using the phylum project name might be a good way to identify the repository they're in at the moment.

Generally this is pretty basic information that I can definitely see being useful to *some* people in the future. I'd much rather provide it here than seeing people start parsing the file themselves.

This will become especially useful if we decide to add the lockfile path to the project settings at some point.
