### ISSUE TITLE
Improve error message for non-existent project

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#653]
# Overview
When attempting to submit an analysis job with a project that doesn't exist, the user receives a 404 error that is unlikely to clarify the issue. This case is more common now as a user can delete a project, but not delete the `.phylum_project` file and run the `analyze` command.

# How To Reproduce
Steps to reproduce this behavior:
1. Create a project
2. Submit a file for analysis
3. See success
4. Delete the project, but do not delete the `.phylum_project` file
5. Run the analysis command again
6. See the 404 error 

# Expected Behavior
A more helpful error message so the user can troubleshoot their situation - ideally, clearly stating that the project does not exist.

# Additional Context
![image](https://user-images.githubusercontent.com/34108612/186444628-3bf215a1-f284-43e3-bfd2-451dabe56771.png)

Related API change: https://github.com/phylum-dev/api/issues/457
Closing this issue should be the last piece of this Story: https://github.com/phylum-dev/roadmap/issues/35

**Comment by kylewillmon** [comment]
This may be completed on the API side instead via phylum-dev/api#478

Since the API fix would be preferred, we should hold off and see what happens with that ticket before making changes on our side.

**Comment by kylewillmon** [comment]
The error message is much better now:

```
❯ phylum analyze requirements.txt
✅ Identified lockfile type: pip
❗ Error: HTTP request error (400 Bad Request):

Could not find project with id: ed40ce27-db36-4665-83e6-edd7c363c03a
```
