### ISSUE TITLE
SBOM extension should support exporting license info in spdx format

### ISSUE THREAD

**Issue by DanielJoyce** [phylum-dev/cli#659]
# Overview
https://spdx.org/licenses/

We have our license heuristic and naming scheme. When CLI extension is generating SBOMs, it shoudl convert it to the SPDX format for each license

# Acceptance Criteria
- [ ] SPDX output formats license info using SPDX identifiers

## Associated User Story
https://github.com/phylum-dev/roadmap/issues/134

**Comment by kylewillmon** [comment]
This should be a comment on the appropriate roadmap ticket and not an issue in this repository. We do not yet have an SBOM extension and so thoughts about its future behavior are misplaced here.

**Comment by louislang** [comment]
FYI @kylewillmon https://github.com/phylum-dev/cli/tree/louis/sbom-extension

But I think the effort to normalize to SPDX should occur on the backend, not in the extension or API itself.
