### ISSUE TITLE
Command line argument `--no-check-certificate` is saved to config

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#664]
# Overview
Setting `--no-check-certificate` on the command line gets saved to the config so that all future runs no longer check certificates. And since we do not have a `--check-certificate` option (see #483), the only way to get phylum to start checking certificates again is to manually modify the config file. This is very similar to #582

# How To Reproduce
```
❯ grep 'ignore_certs' ~/.config/phylum/settings.yaml 
ignore_certs: false

❯ phylum --no-check-certificate ping
[2022-09-02T15:12:10Z WARN  phylum] Ignoring TLS server certificate verification per user request.
✅ alive!

❯ grep 'ignore_certs' ~/.config/phylum/settings.yaml
ignore_certs: true
```

# Expected Behavior
Config from command line arguments or environment variables should never be written out to the config file.

**Comment by kylewillmon** [comment]
I am more and more convinced that we should only write to the config file in a very limited set of circumstances (i.e., `phylum auth login`).

Anything that needs to be updated by our tool more often (i.e., the `last_update` timestamp) should be stored in a state file (probably in the `$XDG_STATE_HOME` folder).

**Comment by cd-work** [comment]
I don't think we should be writing files to `$XDG_STATE_HOME` tbh. But we could probably still shave down on our number of config writes.
