### ISSUE TITLE
Change the license from MIT to GPLv3+

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#688]
## Description

The license for this repository/project needs to change from the current MIT license to the [GNU General Public License (GPL)](https://www.gnu.org/licenses/gpl-3.0-standalone.html) v3.0 or later.

## Additional Details

This change is directed towards all public repositories in the `phylum-dev` organization (with the exception of forked repos).

## Acceptance Criteria

- [x] The license is changed to GPLv3+
- [x] Documentation is updated

**Comment by maxrake** [comment]
@mathew-horner , Are you good with this change? A search of committers shows that you are the only one who made a contribution to this repository without also being an employee of Phylum, Inc.

**Comment by mathew-horner** [comment]
I consent to the license change :)
