### ISSUE TITLE
Sandbox layering and improvements

### ISSUE THREAD

**Issue by andreaphylum** [phylum-dev/cli#692]
# Overview
Currently, there are two independent sandboxes: one enforced by Deno which pertains to its calls, and one enforced by the OS.
The latter is intended for sandboxing invoked commands. We need to integrate the two sandboxes, making sure the OS sandbox doesn't have more privileges than the Deno sandbox.

# Acceptance Criteria
- [ ] `Deno.run` should not be accessible from an extension; the user should use `PhylumApi.runSandboxed` instead (note: check deno.rs:40).
- [ ] If permissions specified in `runSandboxed` are not a subset of the ones in `PhylumExt.toml`, an error should be emitted and the operation should not be allowed.

**Comment by kylewillmon** [comment]
If possible, instead of completely removing `Deno.run`, we should replace it with a version that calls `PhylumApi.runSandboxed` with the permissions from the manifest.

**Comment by andreaphylum** [comment]
> If possible, instead of completely removing `Deno.run`, we should replace it with a version that calls `PhylumApi.runSandboxed` with the permissions from the manifest.

I feel like replacing that call could surprise users if it ends up behaving slightly differently than the default one they expect. Not having it at all would be instead noticeable by the users who would then be prompted to look for documentation. I'll look into it anyway and then we can circle back to it once we have more context.
