### ISSUE TITLE
Replace `ansi_term` with `termcolor` or `console`

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#696]
We are currently using [`ansi_term`](https://crates.io/crates/ansi_term) for color terminal output, which is now abandoned.

Thanks to our use of [`dialoguer`](https://crates.io/crates/dialoguer), we are already pulling in [`console`](https://crates.io/crates/console), which can also handle terminal color printing.

So in order to shorten our list of dependencies and avoid relying on abandonware, we should switch to `console` for all of our color terminal output.

**Comment by kylewillmon** [comment]
We are also already pulling in [`termcolor`](https://crates.io/crates/termcolor), which is more popular than `console` and may be a slightly better option.

**Comment by AntoniosBarotsis** [comment]
Hello! Is this still open? I could probably work on it tonight/tomorrow!

**Comment by maxrake** [comment]
@AntoniosBarotsis, yes, this is still open and we would very much welcome the contribution!

**Comment by AntoniosBarotsis** [comment]
I just started looking into this. The `termcolor` has a very *manual* API if I can call it that while `console` is a lot closer to `ansi_term`.

Of course, the choice is up to you, just wanted to make sure you read through their docs to check some example usage :)

**Comment by cd-work** [comment]
Looking at the docs, neither of these seem to provide a *good* API in my opinion, but I think we'd probably be better served with `console` than `termcolor`.
