### ISSUE TITLE
Bump `deno_*` crates versions

### ISSUE THREAD

**Issue by andreaphylum** [phylum-dev/cli#707]
We may want to check how the recent releases of the `deno_*` crates could impact our permissions system, and whether integrating them can result in improvements in ergonomics or functionality for extensions over the current versions.

There are some breaking changes in a few types (`BootstrapOptions`, `WorkerOptions` and `PermissionsOptions`) and some of their associated functions.

We should evaluate the following updates:
```
deno_runtime 0.71.0  ->  0.79.0
deno_core    0.145.0 -> 0.153.0
deno_ast     0.17.0  ->  0.19.0
```

**Comment by kylewillmon** [comment]
Hmm... I thought dependabot would alert us about these sorts of updates...

Maybe [ignoring](https://github.com/phylum-dev/cli/blob/ac661f601bbef4086f7b93ff41d59891539d0262/.github/dependabot.yml#L9) `semver-minor` updates means that 0.x dependencies are never bumped?

**Comment by andreaphylum** [comment]
IIRC, for all 0.x versions, any semver-minor bump is treated as a potentially breaking change, and only patch updates are considered non-breaking, and with that rationale it does make sense not to bump minor versions. I found that this is most often the case, with crates starting to be non-breaking on the minor patch only once their 1.x releases.
