### ISSUE TITLE
Verbose flag

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#722]
We currently manage logging with the `RUST_LOG` environment variable, but a `-v` flag for verbosity might be more natural for most users.

~~We can consider using the [`clap-verbosity-flag`](https://crates.io/crates/clap-verbosity-flag) crate as a simple way to add this option.~~

**Comment by cd-work** [comment]
I don't think it's necessary to pull a dependency for a clap flag? This is absolutely trivial to implement ourselves.

**Comment by kylewillmon** [comment]
I agree with that. And after a second look, I think that crate only works with `clap`'s derive pattern anyways.

**Comment by cd-work** [comment]
Yeah the flag levels make sense to me.
