### ISSUE TITLE
`phylum history current` causes error/panic

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#751]
# Overview

Running the `phylum history current` command causes an error or panic, depending on which version is used.

# How To Reproduce
Steps to reproduce this behavior:
1. Run the command `phylum history current`
2. See error on current released version (v3.10.0) or panic on current main (v3.10.0-29-g1702bd8)

# Expected Behavior

Information about the most recent job is displayed.

# Additional Context

Here is the output from the current released version:

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/18729796/195706882-40d34663-f0e2-4a13-bd7d-4f939aa5f3df.png">

...and current `main`:

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/18729796/195707672-56d97fb5-553f-4f1f-8897-ea247e40d4cd.png">

**Comment by kylewillmon** [comment]
The `phylum history current` feature was broken for a long time and then removed in #521

> This also removes the alias for "current" as the latest job ID, since
this API changed due to the request manager removal.

So we can simply remove that note from the help output.

The panic that you are seeing on main seems to be a separate issue and needs to be addressed.

**Comment by cd-work** [comment]
The `panic` is because `current` is not a valid UUID. So it's the same issue.
