### ISSUE TITLE
Consider using tags for git dependencies

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#762]
Our git dependencies often cause breakage during `cargo update` or `cargo install` (without `--locked`) because they are not versioned.

One possible solution for this is to use tags instead of branches like in the following example:

```
phylum_types = { git = "https://github.com/phylum-dev/phylum-types", branch = "v0.1.2" }
```

> Honestly I just think it's a good idea to always specify the git hash you're building against when running against git repositories. In fact I generally build against tagged commits since those can't be easily dropped by force-pushing.

_Originally posted by @cd-work in https://github.com/phylum-dev/cli/pull/759#discussion_r998617635_

**Comment by kylewillmon** [comment]
I have one remaining question before we implement this: Is there a way to automate updates for these dependencies?

Currently, our dependencies are bumped in our weekly `cargo update` or by PRs opened by  @dependabot. I am concerned that switching to tags might cause us to forget about updates to our git dependencies.

**Comment by cd-work** [comment]
I mean a tag doesn't really have any update path, so in that case there wouldn't be any way.

But how useful is an automatic bump anyway when the bot has no knowledge of it being a breaking change or not? Ideally we'd have actually versioned crates of course, that way @dependabot would never get confused. At the end of the day there's a very good reason why people came up with the idea of versioning software.

**Comment by kylewillmon** [comment]
> But how useful is an automatic bump anyway when the bot has no knowledge of it being a breaking change or not?

Not useful at all. And it's exactly what we've already got...

But tags can indicate a semantic version. I was hoping that I missed some magic way to make the tools pay attention to that version.

> At the end of the day there's a very good reason why people came up with the idea of versioning software.

I completely agree. We should be properly versioning our library crates. But is there a way to do that when they are git dependencies. Or does that require publishing them to crates.io?

**Comment by cd-work** [comment]
> I completely agree. We should be properly versioning our library crates. But is there a way to do that when they are git dependencies. Or does that require publishing them to crates.io?

That does generally require publishing to crates.io, but honestly I see no reason why we wouldn't. I mean we could in theory also make our own registry, but I really don't see why. `phylum-types` is internal, but already namespaced due to the `phylum-` prefix. `birdcage` isn't namespaced, but doesn't need to be. It would be perfectly acceptable to push both of these to crates.io, I don't see them disappearing anytime soon.

**Comment by kylewillmon** [comment]
Agreed. I have created phylum-dev/birdcage#19 to track publishing it to crates.io

`phylum-types` is likely to undergo massive changes in the near future, so I am going to hold off on that one.

Either way, I am closing this issue.

**Comment by cd-work** [comment]
> phylum-types is likely to undergo massive changes in the near future, so I am going to hold off on that one.

To be fair, that's exactly what `0.Y.Z` versions are for. So if we get birdcage on crates.io, I see no reason why we would hold off on `phylum-types` just because it might change in the future.
