### ISSUE TITLE
Extension exception execution examination

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#775]
Strange things are happening...

```
❯ cat PhylumExt.toml 
name = "exceptional"

[permissions]
run = true

❯ cat main.ts 
import { PhylumApi } from 'phylum';

function do_the_thing(f) {
    try {
        f()
        console.log("thing done!");
    } catch (e) {
        console.log(e);
    }
}

console.log("=== Deno.run ===");
do_the_thing(() => Deno.run({cmd: ["blargle"]}));

console.log("=== PhylumApi.runSandboxed ===");
do_the_thing(() => PhylumApi.runSandboxed({cmd: "blargle", args: [], exceptions: {}}));

❯ phylum extension run --yes ./
=== Deno.run ===
Error: No such file or directory (os error 2)
    at opRun (deno:deno_runtime-0.79.0/js/40_process.js:33:16)
    at Object.run (deno:deno_runtime-0.79.0/js/40_process.js:116:17)
    at file:///Users/kyle/code/cli/extensions/exceptional/main.ts:11:23
    at do_the_thing (file:///Users/kyle/code/cli/extensions/exceptional/main.ts:4:9)
    at file:///Users/kyle/code/cli/extensions/exceptional/main.ts:11:1
=== PhylumApi.runSandboxed ===
Error: No such file or directory (os error 2)
    at Object.opSync (deno:core/01_core.js:190:23)
    at Function.runSandboxed (deno:phylum:343:26)
    at file:///Users/kyle/code/cli/extensions/exceptional/main.ts:17:28
    at do_the_thing (file:///Users/kyle/code/cli/extensions/exceptional/main.ts:4:9)
    at file:///Users/kyle/code/cli/extensions/exceptional/main.ts:17:1
thing done!
```

Why is "thing done!" printed? The catch runs, but then it resumes back at the function? I cannot begin to explain this...

**Comment by cd-work** [comment]
As far as I know, `Deno.run` is actually async, so might want to add an await there just to have it consistent.

**Comment by kylewillmon** [comment]
> As far as I know, `Deno.run` is actually async, so might want to add an await there just to have it consistent.

[`Deno.run`](https://doc.deno.land/deno/stable/~/Deno.run) is synchronous. The `Process` object that it returns has some async methods, but the exception is occurring before that return, so there is nothing to await.

At least that is my understanding... This issue has me questioning my understanding of javascript...

**Comment by andreaphylum** [comment]
```ts
import { PhylumApi } from "phylum";

async function do_the_thing(f) {
  try {
    await f();
    console.log("thing done!");
  } catch (e) {
    console.log(`Catch: ${e}`);
  }
}

console.log("=== Deno.run ===");
await do_the_thing(async () => {
  console.log("Before Deno.run");
  let p = Deno.run({ cmd: ["blargle"] });
  console.log("After Deno.run");
  await p.status();
  console.log("After await status");
});

console.log("=== PhylumApi.runSandboxed ===");
await do_the_thing(async () => {
  console.log('Before runSandboxed')
  PhylumApi.runSandboxed({ cmd: "blargle", args: [], exceptions: {} });
  console.log('After runSandboxed')
});
```

```
❯ phylum extension run -y .
=== Deno.run ===
Before Deno.run
Catch: Error: No such file or directory (os error 2)
=== PhylumApi.runSandboxed ===
Before runSandboxed
❗ Error: No such file or directory (os error 2)
After runSandboxed
thing done!
```

Added more log spots. `Deno.run` doesn't need to be async as it's the (sync) creation of the `Process` object which fails. `Phylum.runSandboxed` is definitely _not_ async and from that it looks like one of these two cases:
1. The exception is printed and consumed on the Rust side and never makes it to JS.
2. The exception is propagated as part of the `Result<ProcessOutput>` return value of the `run_sandboxed` op, but it is not converted to a JS-land exception.

**Comment by andreaphylum** [comment]
This raises and catches the exception as intended:
```ts
// Manifest permissions are read: ['/tmp']
try {
  PhylumApi.runSandboxed({ cmd: 'ls', args: ['/etc'], exceptions: { read: ['/etc'] } })
} catch (e) {
  console.log(`catch: ${e}`)
}
```
```
catch: Error: Invalid read permissions: The following paths are denied by the manifest: /etc
```

The most likely culprit is the fact that we now wrap the execution in `phylum sandbox`:
```rust
    // Execute sandboxed command.
    let output = Command::new(env::current_exe()?)
        .args(sandbox_args.iter_mut().map(|arg| arg.to_mut()))
        .stdin(stdin)
        .stdout(stdout)
        .stderr(stderr)
        .output()?;
```
So the error is printed by `phylum sandbox` on its stderr but not raised as an exception.

A solution I don't love but may be necessary is to use a special error exit code in `phylum sandbox`, catch that in `run_sandboxed`, wrap the stderr into an `Err(_)` and return that to the JS side.

**Comment by kylewillmon** [comment]
As @cd-work mentioned, the behavior in the initial report was caused by a special case in our usage of `fork`. Specifically, we were hitting a case where the child process would return from the function after the call to `fork` which led to the odd behavior.

> It probably makes sense to at least somewhat differentiate between death due to child process failure and death due to child creation error

This is separate and I will open a new issue for this.
