### ISSUE TITLE
Allow disabling self-update

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#782]
Many package managers, such as Homebrew, [don't like tools that upgrade themselves](https://docs.brew.sh/Acceptable-Formulae#we-dont-like-tools-that-upgrade-themselves).

We hope to support Homebrew soon, so we need a way to disable `phylum update` (and `phylum uninstall`) when installed by Homebrew.

I think the simplest way to accomplish this is with a feature flag, but I am open to other suggestions.

**Comment by cd-work** [comment]
We already have a feature flag exactly for this, right? It should be called `selfmanage`?

**Comment by kylewillmon** [comment]
I forgot about the `selfmanage` feature flag. But it looks like it only disables `phylum uninstall` and not `phylum upgrade`.

Once we fix that, it should be exactly we need for this.
