### ISSUE TITLE
Add a `phylum status` subcommand

### ISSUE THREAD

**Issue by cd-work** [phylum-dev/cli#842]
Currently the only way to print information about the linked project is to traverse the directory tree upwards and look for a `.phylum_project` file. This is very awkward and not reliable unless the user knows something about Phylum CLI internals.

A simple subcommand printing information about the current phylum status would likely be helpful. It should definitely include the linked project so users know where they're submitting their data to.

Possible other useful information is basically everything that is part of the lockfile.

**Comment by louislang** [comment]
I think this is a great idea! @furi0us333 any thoughts on this?

**Comment by kylewillmon** [comment]
If we include detected lockfiles in the output and have an option for JSON output, this will also satisfy #982

And since #982 is likely the simplest way to get manifest file support in `phylum-ci`, I think the priority of this issue has gone up significantly
