### ISSUE TITLE
`go` and `cargo` parsers should be hidden

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#844]
The addition of Go and Rust support is still ongoing. As such, the `go` and `cargo` parsers are experimental and not yet supported on the production backend. We should hide these options from the help and docs until they are ready for general usage.

**Comment by louislang** [comment]
The last PR we needed for `go` and `cargo` support was just merged in. These languages are going to be tested in staging tomorrow and go live this weekend. We should be good to just leave them active in the CLI.

**Comment by kylewillmon** [comment]
As mentioned, these languages are now live and this issue is no longer relevant.
