### ISSUE TITLE
Sporadic test failures

### ISSUE THREAD

**Issue by cd-work** [phylum-dev/cli#851]
I've encountered this locally a couple of times and have seen CI fail for the same reason. It would probably be a good idea to look into this sporadic test failure:

```
thread 'extensions::create_extension' panicked at 'Unexpected failure.
code-1
stderr=```"❗ Error: Failed to read configuration at `/Users/phylum/.config/phylum/settings.yaml`: missing field `connection`\n"```
command=`"/Users/phylum/actions-runner/_work/cli/cli/target/debug/phylum" "extension" "new" "my-ext"`
code=1
stdout=""
stderr="❗ Error: Failed to read configuration at `/Users/phylum/.config/phylum/settings.yaml`: missing field `connection`\n"
', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If it was a network error sporadic failure should kind of be expected, but this seems to be something filesystem related which should be preventable. My best guess would be that we're modifying the config from one test while reading it from another?

**Comment by kylewillmon** [comment]
> My best guess would be that we're modifying the config from one test while reading it from another?

Running `phylum` often writes the config. I wonder if we might hit this same condition when simply running `phylum` multiple times in parallel?

**Comment by cd-work** [comment]
> Running phylum often writes the config. I wonder if we might hit this same condition when simply running phylum multiple times in parallel?

I'd assume so honestly. I'm also pretty sure our writes aren't atomic so that likely increases failure chances when relying on config files in a test.

**Comment by kylewillmon** [comment]
This is happening occasionally on the self-hosted running in CI as well. See [this example](https://github.com/phylum-dev/cli/actions/runs/3802170412/jobs/6467383762).
