### ISSUE TITLE
Submit single package

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#871]
The API now supports [submitting a single package for analysis](https://api.staging.phylum.io/api/v0/swagger/index.html#/Packages/packages_submit_endpoint). This functionality should be made accessible from the CLI.

For example, we could add this directly to `phylum package` with a `--submit` flag.
```
phylum package --submit -t npm some-old-package 0.0.1
```

I welcome alternative suggestions for where we should add this functionality.

**Comment by mathew-horner** [comment]
Until https://github.com/phylum-dev/api/issues/667 is done, users will be able to submit _any_ package triple they want and it will trigger a download request. I just want to make sure everyone is aware of that before we roll out a CLI feature for it.

@kylewillmon @furi0us333

**Comment by cd-work** [comment]
@kylewillmon Can you elaborate on the usecases of "submitting" a single package versus just the existing package analysis?

Is it just that the existing one doesn't start an analysis if it hasn't been analyzed yet? If so, shouldn't we handle this automatically for the user instead of forcing the usage of a flag?

Also is there any drawback to submission over just retrieving the result? Will it **always** reanalyze and thus be expensive or will this return an existing result if a package was already analyzed?

And analysis itself of course takes 15+ minutes usually. Do we want to provide results immediately? Usually we don't, so we'd probably just tell the user to check back later?

**Comment by kylewillmon** [comment]
Let me provide some quick answers first.

> Is it just that the existing one doesn't start an analysis if it hasn't been analyzed yet?

Yes. This is correct.

> Also is there any drawback to submission over just retrieving the result? Will it **always** reanalyze and thus be expensive or will this return an existing result if a package was already analyzed?

As I understand it, this will not reanalyze a package. It is only for submitting packages that have not yet been analyzed.

> And analysis itself of course takes 15+ minutes usually. Do we want to provide results immediately? Usually we don't, so we'd probably just tell the user to check back later?

This is right. We should not wait around for results and should just instruct the user to check back later.

**And now the big question**

> If so, shouldn't we handle this automatically for the user instead of forcing the usage of a flag?

I had not thought of this. But I don't see why not. With the current API, this would require 2 round trips. But that could be fixed (either now or later) by updating the `POST /data/packages/submit` endpoint to return the package if it already exists.

This would also resolve confusion about non-existent packages and packages that are currently being processed. If we always submit the package, then there are three possible responses:

1. Error for a non-existent package (phylum-dev/api#667)
1. A pending status for packages that are currently being processed
1. Results for packages that have been analyzed

This is much better than the current endpoint which provides the same response for any package that has not been analyzed. Which means that it returns the same result for a non-existent package, a yet-to-be submitted package, and an in-processing package.

@louislang: Is there any reason not to make package submission the default behavior of the `phylum package <name> <version>` command?

Additionally, if we submit by default, should we offer something like a `--check-only` flag to avoid submission?

**Comment by mathew-horner** [comment]
> But that could be fixed (either now or later) by updating the POST /data/packages/submit endpoint to return the package if it already exists.

This is the current behavior. [There are 3 variants that get returned in the `status` field of the response and it will return the package data if we have already processed the package.](https://api.staging.phylum.io/api/v0/swagger/index.html#/Packages/packages_submit_endpoint)

**Comment by louislang** [comment]
> @louislang: Is there any reason not to make package submission the default behavior of the phylum package <name> <version> command?

Not that I'm aware of. This sounds like a better user experience in my opinion. Curious if @furi0us333 has any thoughts from customer pov

**Comment by furi0us333** [comment]
Assuming we have the "currently being processed" status info, this sounds great to me and I can't see a reason to require any additional flags.
