### ISSUE TITLE
Yarn/Poetry extensions will break when subcommand is not first argument

### ISSUE THREAD

**Issue by cd-work** [phylum-dev/cli#896]
Currently to determine if an install is taking place, the first argument is inspected and compared against the known arguments. This will however break when executing something like `yarn --cwd=/tmp/project install`. Unfortunately this will fail in an unsafe manner, not actually checking the dependencies, rather than just not running the command at all.

We should make sure every way to reach the `install` command for each respective ecosystem is covered by our argument parser, to ensure at the very least we can fail when something is not understood or print a warning.

My understanding from looking at `npm --help` is that the `npm` extension is unaffected by this, since it does not allow any arguments before the first subcommand.

**Comment by kylewillmon** [comment]
Hmm... And I assume `yarn --cwd /tmp/project install` is also valid. So we can't just use the first argument that doesn't start with a hyphen... This might get a bit tricky...

**Comment by cd-work** [comment]
Yes correct, we'd have to implement an actual parser for all the commands.

I'll put up a PR for the `pip` extension tomorrow which will include at least a preliminary solution to this issue.
