### ISSUE TITLE
Add support for multiple lockfiles in parse/analyze/init CLI

### ISSUE THREAD

**Issue by cd-work** [phylum-dev/cli#906]
Currently if a user wants to analyze multiple lockfiles at once, they **must** use the `.phylum_project` file. It should be possible to do the same using only command line flags.

The main issue with this is that while `--lockfile` could easily be specified multiple times, the associated `--lockfile-type` can no longer be stored separately since it requires some association to one of the lockfiles.

One option would be to switch the lockfile to `npm:package-lock.json` instead, where an optional ecosystem prefix is allowed in the `--lockfile` to force a given ecosystem.

**Comment by louislang** [comment]
while encoding structure in the string is _probably_ more error prone (e.g., 'npm;package-lock.json' is likely a common typo), I'm not really sure if there is a cleaner/better way to handle that. I think it makes a lot of sense and isn't particular onerous.
