### ISSUE TITLE
Rubygems parser seems broken

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#918]
# Overview
Attempting to parse a `Gemfile.lock` seems to always result in an error.

# How To Reproduce
Steps to reproduce this behavior:
1. Grab a sample `Gemfile.lock` ([sample](https://raw.githubusercontent.com/ambethia/recaptcha/master/Gemfile.lock))
2. Run `phylum parse Gemfile.lock`
3. See error

# Expected Behavior
Properly parse gem lockfiles.

# Additional Context
![image](https://user-images.githubusercontent.com/34108612/213246806-444f8a53-be2b-4646-a4d9-a0ab453f51d9.png)

**Comment by cd-work** [comment]
Nice find, I wasn't aware sub-dependencies without version are legal.

I've opened a patch here that should parse your file without any problem:
https://github.com/phylum-dev/cli/pull/919
