### ISSUE TITLE
Improve interactive interface of `phylum init`

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#935]
# Overview
There are reports of confusion by users on how to work with the interactive interface of the `phylum init` command:

* Not knowing or understanding that the default value is the one displayed in brackets and will be used if `<ENTER>` is pressed with no other input
* When selecting lockfiles interactively from the pre-populated list it is not clear that `<SPACE>` will select the lockfile entry and `<ENTER>` will move to the next section
  * `<ENTER>` is a common keystroke seen on this menu when a new user is expecting that action to select a file and is then surprised when it moves on to the next section
* When no lockfile(s) is/are detected, `phylum init` presents this prompt instead of a list of choices: `Other lockfiles (comma separated): `
  * <img width="759" alt="image" src="https://user-images.githubusercontent.com/18729796/216513043-521a64e8-cf5b-4edc-90d8-38009616217d.png">
  * Without the context of the alternative interface (where a list of lockfiles are presented), the phrasing is confusing...like it suggests that a lockfile was _automatically_ selected but not displayed and now the user can provide more/other lockfiles _manually_
  * One suggestion is to update the text to say `Comma separated lockfile paths: ` and also make it more clear that no lockfiles were _detected_ and that this is the chance to specify one or more manually

# Acceptance Criteria
- [ ] Instructions for using the `phylum init` command are provided in the `--help` output, during the interactive prompts, and in online (`.md` files hosted on readme.com) documentation
- [ ] Output from executing the `phylum init` command is more clear, as accepted by @furi0us333

**Comment by louislang** [comment]
I think giving a general hint at the start of the output would also go a long way to clarifying some behavior, for example:

```
Press ENTER to accept defaults in [brackets] or enter your own value.
```

A simple fix for lockfile selection might also be similar:

```
Press SPACE to toggle a selection and ENTER to continue

Select your project's lockfile:
> [ ] package-lock.json
  [ ] others

```

If no lockfiles are found, you land on the `Other lockfiles (comma separated):`. Pressing ENTER here has no effect; it feels like something is stuck/unresponsive after having pressed ENTER a few times to accept defaults. In addition to changing the text in this case, we should notify the user that no lockfiles could be found:

```
We could not automatically identify any lockfiles, please enter comma separated lockfile paths.

Lockfile paths (comma separated):
```

Additionally, ENTER should probably have some action in the event the user hasn't entered anything, e.g.

```
Lockfile paths (comma separated):: <ENTER>

Please specify at least one lockfile

Lockfile paths (comma separated):
```
