### ISSUE TITLE
Support parsing SPDX SBOMs

### ISSUE THREAD

**Issue by ejortega** [phylum-dev/cli#949]
# Overview
Users should be able to submit SPDX Software Bill of Materials (SBOMs) for analysis.

# Acceptance Criteria
- [ ] Parsing of common SBOM file formats (JSON, YAML)
- [ ] Extract the relevant dependencies for ecosystems we currently support
- [ ] Handle any errors or warnings in the SBOM file and provide clear error messages to the user

## Additional Context
https://github.com/spdx/spdx-spec/tree/master
https://spdx.dev/specifications/

**Comment by cd-work** [comment]
This will basically mean https://github.com/phylum-dev/community-extensions/tree/main/sbom redundant, right?

**Comment by ejortega** [comment]
> This will basically mean https://github.com/phylum-dev/community-extensions/tree/main/sbom redundant, right?

I would say not necessarily. That extension takes a lockfile, submits dependencies for analysis, and generates an SBOM artifact. (which could be ingested when this ticket is complete).

This ticket is to have the  CLI  support SPDX formatted SBOMs (in the available SPDX formats), that have been generated by some other means.

We could write additional tickets for each SPDX format. Thought I'd put it all in one for now, but can break up into smaller tasks if needed.
