### ISSUE TITLE
Make `--package-type` a required option for the `phylum package` command

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#996]
# Overview
Not requiring the type yields confusing results as the CLI will just choose for you without context.

# Acceptance Criteria
- [ ] The `phylum package` command requires a proper `--package-type` input

**Comment by maxrake** [comment]
Here is an example:

<img width="982" alt="image" src="https://user-images.githubusercontent.com/18729796/229158130-507d9de7-32c9-4d4c-9cd1-e528e7f15c4a.png">
